import {loadModel} from '../atlas/asset-loading.js';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {CITIES} from '../atlas/atlas-ui-data.js';
import {createThemeGate} from './theme-gate.js';
import {createThemeEnvironment} from './theme-environment.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
export function createDiorama(container,{onEnter,onLoading,onSelect,onOverviewProgress,onLabels}){
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.info.autoReset=false;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;container.append(renderer.domElement);
 const scene=new T.Scene();scene.background=new T.Color('#101b29');scene.fog=new T.FogExp2('#101b29',.019);const camera=new T.PerspectiveCamera(42,innerWidth/innerHeight,.1,100);camera.position.set(11,8,16);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,2,0);controls.enablePan=false;controls.enableDamping=true;controls.minDistance=13;controls.maxDistance=27;controls.minPolarAngle=.4;controls.maxPolarAngle=1.48;controls.update();
 const ambient=new T.HemisphereLight('#b8c9ed','#25223d',1.5);scene.add(ambient);const sun=new T.DirectionalLight('#ffdfb1',2.0);sun.position.set(7,12,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12,near:1,far:40});sun.shadow.normalBias=.025;scene.add(sun);const rim=new T.DirectionalLight('#987cfa',2.4);rim.position.set(-7,5,-6);scene.add(rim);
 const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.48,.55,1.15);composer.addPass(bloom);composer.addPass(new OutputPass());
 const stars=[];for(let i=0;i<550;i++){const a=i*2.399,r=35+Math.sin(i*13)*8;stars.push(Math.cos(a)*r,Math.sin(i*4.7)*23+10,Math.sin(a)*r);}const sg=new T.BufferGeometry();sg.setAttribute('position',new T.Float32BufferAttribute(stars,3));scene.add(new T.Points(sg,new T.PointsMaterial({color:'#93afc8',size:.055,transparent:true,opacity:.42,depthWrite:false})));
 const root=new T.Group();scene.add(root);const entries=new Map(),cache=new Map(),loader=new GLTFLoader(),ray=new T.Raycaster(),pointer=new T.Vector2();let model=null,id='theme',token=0,anim=true,reduced=false,transition=null,time=0,last=performance.now(),raf,disposed=false,start=null,objects=null;
 const themeGate=createThemeGate();root.add(themeGate.group);
 const themeEnvironment=createThemeEnvironment(themeGate.materials.stone);root.add(themeEnvironment.group);
 const room=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),environmentMap=pmrem.fromScene(room,.04);room.dispose();pmrem.dispose();
 function themeLighting(enabled){camera.far=enabled?300:100;camera.updateProjectionMatrix();themeEnvironment.group.visible=enabled;scene.environment=enabled?environmentMap.texture:null;scene.fog.density=enabled?.006:.019;ambient.intensity=enabled?.65:1.5;scene.environmentIntensity=enabled?.55:1;sun.intensity=enabled?1.25:2;rim.intensity=enabled?1.8:2.4;}
 const material=(color,extras={})=>new T.MeshStandardMaterial({color,roughness:.85,...extras});
 function mesh(parent,g,m,p=[0,0,0]){const o=new T.Mesh(g,m);o.position.fromArray(p);o.castShadow=o.receiveShadow=true;parent.add(o);return o;}
 function cylinder(parent,a,b,r,m){const v=new T.Vector3(...b).sub(new T.Vector3(...a)),o=mesh(parent,new T.CylinderGeometry(r*.7,r,v.length(),8),m);o.position.fromArray(a).addScaledVector(v,.5);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),v.normalize());return o;}
 function createSetting(city){
 const g=new T.Group(),stone=material('#4d5666'),ground=material(city.id==='valley'?'#b9cbd5':city.id==='forest'?'#444053':city.id==='watercourt'?'#88938a':'#6c6659'),wood=material('#685044'),trim=material('#b0a07b',{metalness:.25}),snow=material('#e1eaf2'),leaf=material(city.id==='forest'?'#805a9c':city.id==='valley'?'#293f45':'#395753');
 const base=mesh(g,new T.CylinderGeometry(5.4,2.4,2.7,64,10),stone,[0,-1.38,0]),p=base.geometry.attributes.position;for(let i=0;i<p.count;i++){const y=p.getY(i),a=Math.atan2(p.getZ(i),p.getX(i)),k=1+Math.sin(a*9+y*2.5)*.055+Math.cos(a*17)*.025;p.setX(i,p.getX(i)*k);p.setZ(i,p.getZ(i)*k);}base.geometry.computeVertexNormals();mesh(g,new T.CylinderGeometry(5.45,5.2,.35,64),ground,[0,-.05,0]);
 for(let i=0;i<28;i++){const a=i*2.399,r=4.7+(i%3)*.16;const rock=mesh(g,new T.DodecahedronGeometry(.28+(i%4)*.12,0),stone,[Math.cos(a)*r,-.08,Math.sin(a)*r]);rock.scale.set(1.3,.7,1);rock.rotation.set(i,.4*i,.2*i);}
 for(let i=0;i<7;i++)for(let j=0;j<3;j++){const o=mesh(g,new T.BoxGeometry(.43,.1,.38),material(i%2?'#8d8981':'#a7a294'),[(j-1)*.46,.18,1.6+i*.4]);o.rotation.y=Math.sin(i*11+j)*.08;}
 // Fine leaves and layered needles keep the miniature botanical silhouettes readable.
 const leafGeo=new T.SphereGeometry(.11,5,3),leaves=new T.InstancedMesh(leafGeo,leaf,5000),snowBoughs=new T.InstancedMesh(leafGeo,snow,3000),dummy=new T.Object3D();let count=0,snowCount=0;
 for(let i=0;i<7;i++){const a=2.1+i*.58,r=3.65+(i%2)*.65,x=Math.cos(a)*r,z=Math.sin(a)*r,h=2.5+(i%3)*.6;cylinder(g,[x,.15,z],[x-.1,h,z],.12,wood);
 if(city.id==='valley'||city.id==='highland'){for(let k=0;k<6;k++){const radius=(1-k*.14)*.95,yy=.65+k*.43;for(let j=0;j<7;j++){const a=j*Math.PI*2/7+k*.55,dx=Math.cos(a),dz=Math.sin(a);cylinder(g,[x,yy+.17,z],[x+dx*radius,yy-.08,z+dz*radius],.025,wood);for(let n=0;n<10;n++){const t=(n+.8)/11,w=(1-t)*.25,side=n%2?1:-1;dummy.position.set(x+dx*radius*t-dz*w*side,yy+.1-t*.13,z+dz*radius*t+dx*w*side);dummy.rotation.set(.12,a,n*.15);dummy.scale.set(1.9,.55,1.15);dummy.updateMatrix();leaves.setMatrixAt(count++,dummy.matrix);if(city.id==='valley'&&n%2===0){dummy.position.y+=.058;dummy.scale.set(1.9,.27,1.1);dummy.updateMatrix();snowBoughs.setMatrixAt(snowCount++,dummy.matrix);}}}}}
 else{for(let j=0;j<3;j++){const aa=j*2.1+i;cylinder(g,[x,h*.5,z],[x+Math.cos(aa)*.7,h-.2,z+Math.sin(aa)*.7],.055,wood);}for(let j=0;j<600;j++){const aa=j*2.399,rr=Math.sqrt((j+.5)/600)*1.15;dummy.position.set(x+Math.cos(aa)*rr,h+.2+Math.sin(j*17.3)*.55,z+Math.sin(aa)*rr);dummy.rotation.set(j*.5,j*.3,j);dummy.scale.set(1.3,.22,.65);dummy.updateMatrix();leaves.setMatrixAt(count++,dummy.matrix);}}
 }leaves.count=count;leaves.castShadow=true;g.add(leaves);snowBoughs.count=snowCount;snowBoughs.castShadow=true;g.add(snowBoughs);
 // Physical timber fence and lanterns around the entrance, clear of the doorway.
 const lamp=material('#ffd391',{emissive:'#ffc170',emissiveIntensity:1.5});
 for(const s of [-1,1]){for(let i=0;i<4;i++){const z=2+i*.65;mesh(g,new T.BoxGeometry(.11,.76,.11),wood,[s*2.4,.58,z]);if(i<3)for(const y of [.5,.85])mesh(g,new T.BoxGeometry(.065,.07,.65),wood,[s*2.4,y,z+.325]);}cylinder(g,[s*1.6,.2,3.7],[s*1.6,1.9,3.7],.065,wood);mesh(g,new T.BoxGeometry(.28,.4,.28),lamp,[s*1.6,1.83,3.7]);mesh(g,new T.ConeGeometry(.27,.25,4),trim,[s*1.6,2.14,3.7]).rotation.y=Math.PI/4;const light=new T.PointLight('#ffd391',3,5,2);light.position.set(s*1.6,1.85,3.7);g.add(light);}
 for(let i=0;i<100;i++){const a=i*2.399,r=2.9+(i%13)*.16,x=Math.cos(a)*r,z=Math.sin(a)*r;if(z>1.5&&Math.abs(x)<2.6)continue;const o=mesh(g,new T.ConeGeometry(.035,.16+(i%4)*.04,4),city.id==='valley'?snow:leaf,[x,.28,z]);o.rotation.z=Math.sin(i)*.25;}
 const portal=new T.Group();portal.position.set(0,3.25,-2.8);portal.rotation.y=-.08;g.add(portal);
 mesh(portal,new T.TorusGeometry(3.03,.19,8,64),stone);mesh(portal,new T.TorusGeometry(3.08,.04,8,96),trim);
 const ring=mesh(portal,new T.TorusGeometry(2.88,.035,8,128),material(city.color,{emissive:city.color,emissiveIntensity:4,roughness:.2}));
 ring.position.z=.19;
 const veil=mesh(portal,new T.CircleGeometry(2.82,80),new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{t:{value:0},color:{value:new T.Color(city.color)}},vertexShader:'varying vec2 v;void main(){v=uv*2.-1.;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 v;uniform float t;uniform vec3 color;void main(){float r=length(v);float wave=sin(r*9.-t*.7+sin(atan(v.y,v.x)*3.+t*.3)*.6);float edge=pow(r,7.);float alpha=(.012+.018*wave*wave+.22*edge)*smoothstep(1.,.97,r);gl_FragColor=vec4(color*(.65+edge),alpha);}'}));
 const points=[];for(let i=0;i<230;i++){const a=i*2.399,r=2.89+Math.sin(i*71)*.11;points.push(Math.cos(a)*r,Math.sin(a)*r,(Math.sin(i*39)*.35));}const pg=new T.BufferGeometry();pg.setAttribute('position',new T.Float32BufferAttribute(points,3));const sparks=new T.Points(pg,new T.PointsMaterial({color:city.color,size:.035,transparent:true,opacity:.9,blending:T.AdditiveBlending,depthWrite:false}));portal.add(sparks);
 batchSetting(g,portal);return{group:g,portal,ring,veil,sparks};
 }
 function batchSetting(group,portal){
  group.updateMatrixWorld(true);const batches=new Map();
  // Bake repeated posts, paving and branches into material batches once per miniature.
  for(const o of [...group.children]){if(!o.isMesh||o.isInstancedMesh||!o.material.isMeshStandardMaterial)continue;const m=o.material,key=[m.color.getHex(),m.emissive.getHex(),m.emissiveIntensity,m.roughness,m.metalness].join('/');let b=batches.get(key);if(!b)batches.set(key,b={material:m,geometries:[]});const baked=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();b.geometries.push(baked.applyMatrix4(o.matrix));o.removeFromParent();o.geometry.dispose();}
  for(const b of batches.values()){const geometry=mergeGeometries(b.geometries);b.geometries.forEach(g=>g.dispose());if(geometry)mesh(group,geometry,b.material);}
 }
 function prepareEntry(city){
  if(entries.has(city.id))return entries.get(city.id);
  const group=new T.Group();group.name='Homepage miniature · '+city.id;group.userData.city=city.id;const setting=createSetting(city);group.add(setting.group);root.add(group);
  const entry={city,group,setting,model:null,status:'loading',promise:null};entries.set(city.id,entry);return entry;
 }
 function normalizeModel(asset){const m=asset.scene.clone(true),box=new T.Box3().setFromObject(m),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()),scale=6.4/Math.max(size.x,size.z,size.y*1.18);m.scale.setScalar(scale);m.position.set(-center.x*scale,.15-box.min.y*scale,-center.z*scale);m.traverse(o=>{if(o.isMesh)o.castShadow=o.receiveShadow=true;});return m;}
 async function loadEntry(city){const e=prepareEntry(city);if(e.model)return e;if(e.promise)return e.promise;
  e.status='loading';e.promise=(async()=>{try{if(!cache.has(city.id))cache.set(city.id,loadModel(loader,import.meta.env.BASE_URL+'atlas/miniatures/'+city.id+'.glb',{onProgress(p){e.progress=p;if(id===city.id)onLoading(true,null,p);reportOverview();}}).catch(error=>{cache.delete(city.id);throw error;}));const asset=await cache.get(city.id);if(disposed)return e;e.model=normalizeModel(asset);e.group.add(e.model);e.status='ready';if(id===city.id){model=e.model;objects=e.setting;onLoading(false);}}catch(error){e.status='error';if(id===city.id)onLoading(false,error);}finally{e.promise=null;reportOverview();}return e;})();return e.promise;
 }
 function reportOverview(){if(id!=='overview')return;onOverviewProgress?.(CITIES.map(c=>({id:c.id,status:entries.get(c.id)?.status||'pending',progress:entries.get(c.id)?.progress})));}
 function resetCamera(){controls.maxPolarAngle=1.48;controls.enableDamping=false;controls.reset();camera.position.set(11,8,16);controls.target.set(0,2,0);controls.update();controls.enableDamping=true;}
 function overviewLayout(){if(id!=='overview')return;resetCamera();controls.enabled=false;camera.updateMatrixWorld();
  const small=innerWidth<700,slots=small?[[.25,.395],[.75,.395],[.25,.58],[.75,.58],[.5,.765]]:[[.18,.47],[.43,.42],[.75,.51],[.32,.69],[.60,.70]],width=Math.min(innerWidth*(small?.35:.19),260),distance=camera.position.distanceTo(controls.target),worldPerPixel=2*distance*Math.tan(T.MathUtils.degToRad(camera.fov/2))/innerHeight,forward=controls.target.clone().sub(camera.position).normalize(),scale=width*worldPerPixel/11.5;
  const labels=[];CITIES.forEach((c,i)=>{const e=entries.get(c.id);if(!e)return;const [u,v]=slots[i],direction=new T.Vector3(u*2-1,1-v*2,.5).unproject(camera).sub(camera.position).normalize(),position=camera.position.clone().addScaledVector(direction,distance/direction.dot(forward));position.y-=scale;e.group.position.copy(position);e.group.scale.setScalar(scale);e.group.visible=true;e.group.rotation.y=-.10;e.setting.group.traverse(o=>{if(o.isLight)o.visible=false;});labels.push({id:c.id,x:u*innerWidth,y:v*innerHeight+width*.42});});onLabels?.(labels);
 }
 let overviewPromise=null;
 async function overview(){++token;id='overview';themeGate.group.visible=false;themeLighting(false);rim.color.set('#abc8df');model=null;objects=null;transition=null;root.position.y=0;
  // Frames between cities let text and already prepared miniatures become usable immediately.
  if(!overviewPromise)overviewPromise=(async()=>{for(const city of CITIES){if(disposed)return;await new Promise(r=>requestAnimationFrame(r));const e=prepareEntry(city);if(id==='overview')overviewLayout();else e.group.visible=id===city.id;await loadEntry(city);}overviewPromise=null;})();
  overviewLayout();reportOverview();return overviewPromise;
 }
 async function select(next){if(next==='theme')return theme();if(next==='overview')return overview();themeGate.group.visible=false;themeLighting(false);++token;id=next;resetCamera();controls.enabled=true;onLoading(true);const city=CITIES.find(c=>c.id===next),e=prepareEntry(city);for(const [key,item]of entries){item.group.visible=key===next;item.group.position.set(0,0,0);item.group.rotation.set(0,0,0);item.group.scale.setScalar(1);item.setting.group.traverse(o=>{if(o.isLight)o.visible=true;});}objects=e.setting;model=e.model;rim.color.set(city.color);if(model)onLoading(false);else await loadEntry(city);}
 function themeLayout(){if(id!=='theme')return;controls.maxPolarAngle=Math.PI;controls.enableDamping=false;controls.reset();camera.position.set(1.7,innerWidth<700?10:1.1,24);controls.target.set(0,3,0);controls.update();controls.enableDamping=true;controls.enabled=false;camera.updateMatrixWorld();
  const small=innerWidth<700,u=small?.44:.65,v=small?.35:.47,distance=camera.position.distanceTo(controls.target),height=2*distance*Math.tan(T.MathUtils.degToRad(camera.fov/2)),scale=height*(small?.31:.65)/9,forward=controls.target.clone().sub(camera.position).normalize(),direction=new T.Vector3(u*2-1,1-v*2,.5).unproject(camera).sub(camera.position).normalize();
  themeGate.group.position.copy(camera.position).addScaledVector(direction,distance/direction.dot(forward));themeGate.group.position.y-=3.3*scale;themeGate.group.scale.setScalar(scale);themeEnvironment.group.position.copy(themeGate.group.position);themeEnvironment.group.scale.copy(themeGate.group.scale);
 }
 function theme(){++token;id='theme';model=null;objects=null;transition=null;root.position.y=0;for(const e of entries.values())e.group.visible=false;themeGate.group.visible=true;themeLighting(true);rim.color.set('#9ecad8');themeLayout();}
 function resize(){camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<700?67:42;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);if(id==='overview')overviewLayout();else if(id==='theme')themeLayout();}window.addEventListener('resize',resize);resize();
 function down(e){start={x:e.clientX,y:e.clientY};}function up(e){if(!start)return;const s=start;start=null;if(Math.hypot(e.clientX-s.x,e.clientY-s.y)>5||transition)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);if(id==='theme'){if(ray.intersectObject(themeGate.group,true).length)onSelect?.('overview');return;}const hit=ray.intersectObjects([...entries.values()].filter(e=>e.group.visible).map(e=>e.group),true)[0];if(!hit)return;let group=hit.object;while(group&&!group.userData.city)group=group.parent;if(id==='overview'&&group)onSelect?.(group.userData.city);else if(model)onEnter();}renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',()=>start=null);
 function animate(now){if(disposed)return;raf=requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.06);last=now;if(anim&&!reduced)time+=dt;
 if(id==='theme'){themeGate.animate(time);themeEnvironment.animate(time);}
 for(const [key,e]of entries){if(!e.group.visible)continue;const o=e.setting;o.veil.material.uniforms.t.value=time;o.sparks.rotation.z=time*.08;o.sparks.rotation.y=Math.sin(time*.4)*.045;o.ring.material.emissiveIntensity=3.3+Math.sin(time*1.4+CITIES.findIndex(c=>c.id===key))*.5;}
 root.position.y=id==='overview'||id==='theme'||reduced||!anim?0:Math.sin(time*.6)*.065;
 if(transition){const p=Math.min(1,(now-transition.start)/transition.duration),q=p*p*(3-2*p);camera.position.copy(transition.eye).lerp(transition.end,q);controls.target.copy(transition.target).lerp(new T.Vector3(0,3.1,-2.8),q);if(objects){objects.sparks.scale.setScalar(1+q*.65);objects.ring.material.emissiveIntensity=4+q*10;}if(p===1){const resolve=transition.resolve;transition=null;resolve();}}
 if(id!=='overview'&&id!=='theme')controls.update();renderer.info.reset();composer.render();
 }raf=requestAnimationFrame(animate);
 return{select,overview,theme,themeGate,themeEnvironment,renderer,scene,camera,controls,entries,get model(){return model;},get selected(){return id;},applySettings(s){anim=s.motion;reduced=s.reduced;themeEnvironment.quality(s.quality);const ratio={low:.75,balanced:1,high:1.5}[s.quality];renderer.setPixelRatio(Math.min(devicePixelRatio,ratio));composer.setPixelRatio(renderer.getPixelRatio());bloom.enabled=s.quality!=='low';},enter(){controls.enabled=false;return new Promise(resolve=>{transition={resolve,start:performance.now(),duration:reduced?60:1400,eye:camera.position.clone(),target:controls.target.clone(),end:new T.Vector3(0,3.4,1.6)};});},dispose(){disposed=true;cancelAnimationFrame(raf);window.removeEventListener('resize',resize);scene.traverse(o=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());});themeEnvironment.dispose();environmentMap.dispose();controls.dispose();composer.dispose();renderer.dispose();}};
}
