import {CITIES,icon} from '../atlas/atlas-ui-data.js';
import {createWorldShell} from '../atlas/world-shell.js';
import {createDiorama} from './diorama.js';
import './style.css';
const app=document.querySelector('#home-app');app.innerHTML=`<main class="home-stage" aria-label="五座微缩城镇的三维总览，点击城镇选择入口"></main><a class="home-brand" href="./home.html"><span><svg class="home-compass" viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="1"><circle cx="32" cy="32" r="18"/><ellipse cx="32" cy="32" rx="8" ry="24"/><path d="M32 1L37 27L63 32L37 37L32 63L27 37L1 32L27 27Z M16 16L48 48M16 48L48 16"/></svg></span><div>AETHER<small class="brand-worlds">五座城镇 · 一片世界</small><small class="brand-theme">WORLDS BEYOND WITHIN</small></div></a><section class="home-intro"><small class="home-eyebrow">WORLDS BEYOND WITHIN</small><h1>五座城镇，一片世界。</h1><p>从云上群岛到北境雪谷，选择你的第一站。</p><button class="home-enter" hidden>开启光门 ${icon('arrow')}</button><div class="home-theme-actions"><button class="home-unfold">展开五城 ${icon('arrow')}</button><button class="home-about">关于这片世界</button></div><small class="home-status" role="status"></small><button class="home-retry" hidden>重新加载未完成的城镇</button></section><div class="home-city-labels" aria-label="三维城镇入口">${CITIES.map(c=>`<button data-city="${c.id}" style="--city-color:${c.color}" hidden><strong>${c.name} ›</strong><small>${c.season}</small></button>`).join('')}</div><nav class="home-cities" aria-label="选择城镇"><button data-city="overview"><i></i><span>五城总览</span><small>ALL</small></button>${CITIES.map((c,i)=>`<button data-city="${c.id}" style="--city-color:${c.color}"><i></i><span>${c.name}</span><small>0${i+1}</small></button>`).join('')}</nav><p class="home-theme-motto">一扇门，通往所有远方。</p><p class="home-gesture">点击一座城镇 · 查看光门入口</p><div class="home-passage" aria-hidden="true"></div>`;
const query=new URLSearchParams(location.search);
let selected=CITIES.some(c=>c.id===query.get('city'))?query.get('city'):query.get('view')==='overview'?'overview':'theme',loading=false,failed=false,entering=false,diorama,shell;
function select(id){
 if(entering||(!['theme','overview'].includes(id)&&!CITIES.some(c=>c.id===id)))return;
 selected=id;failed=false;const theme=id==='theme',overview=id==='overview',city=CITIES.find(c=>c.id===id);
 document.body.dataset.homeView=theme?'theme':overview?'overview':'city';
 document.querySelector('.home-stage').setAttribute('aria-label',theme?'五城主题光门，点击光门或展开五城按钮浏览城镇':overview?'五座微缩城镇的三维总览，点击城镇选择入口':city.name+'三维建筑，拖动旋转或点击进入');
 document.querySelector('h1').textContent=theme?'让想象，成为\n可抵达的世界。':overview?'五座城镇，一片世界。':city.name;
 document.querySelector('.home-intro p').textContent=theme?'云上的群岛、松间的山城、紫色的森林、临水的庭院与覆雪的河谷。五座城镇，在同一片世界相遇。':overview?'从云上群岛到北境雪谷，选择你的第一站。':city.text;
 document.documentElement.style.setProperty('--city-color',city?.color||'#c9b78e');
 document.querySelectorAll('.home-cities button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.city===id)));
 document.querySelector('.home-enter').hidden=theme||overview;
 document.querySelector('.home-retry').hidden=true;
 document.querySelector('.home-status').textContent='';
 document.querySelector('.home-gesture').textContent=overview?'点击一座城镇 · 查看光门入口':'拖动旋转 · 点击建筑进入';
 if(theme)loading=false;
 history.replaceState(null,'',location.pathname+(theme?'':overview?'?view=overview':'?city='+id));
 diorama?.select(id);shell?.setRegion(id);
}
async function enter(){if(['overview','theme'].includes(selected)||entering||loading)return;if(failed){diorama.select(selected);return;}entering=true;document.querySelector('.home-enter').disabled=true;document.querySelectorAll('[data-city]').forEach(b=>b.disabled=true);document.body.dataset.entering='true';document.querySelector('.home-status').textContent='光门已开启，正在前往'+CITIES.find(c=>c.id===selected).name+'…';await diorama.enter();location.assign('./aether.html?region='+selected+'&arrival=portal&from=home');}
function overviewProgress(states){if(selected!=='overview')return;const ready=states.filter(s=>s.status==='ready').length,errors=states.filter(s=>s.status==='error').length;loading=ready+errors<5;document.querySelector('.home-status').textContent=ready===5?'五城已呈现 · 点击模型或城名选择入口':`微缩城镇 ${ready} / 5 已就绪，已显示的入口可以先选。`;document.querySelector('.home-retry').hidden=!errors;for(const s of states){const b=document.querySelector(`.home-city-labels [data-city=${s.id}]`);b.dataset.status=s.status;b.title=s.status==='error'?'建筑加载未完成，点击重试':CITIES.find(c=>c.id===s.id).name;}}
try{diorama=createDiorama(document.querySelector('main'),{onEnter:enter,onSelect:select,onOverviewProgress:overviewProgress,onLabels(labels){for(const p of labels){const b=document.querySelector(`.home-city-labels [data-city=${p.id}]`);b.hidden=false;b.style.left=p.x+'px';b.style.top=p.y+'px';}},onLoading(value,error){if(['overview','theme'].includes(selected))return;loading=value;failed=!!error;document.querySelector('.home-enter').disabled=value;document.querySelector('.home-enter').innerHTML=(error?'重新加载城镇':'开启光门')+icon('arrow');document.querySelector('.home-status').textContent=error?'模型暂未加载成功，请点击重试。':value?'正在展开微缩城镇…':'真实三维建筑 · 来自现有城镇';}});const home={get selected(){return selected;},select,applySettings:s=>diorama.applySettings(s)};shell=createWorldShell({home});select(selected);document.querySelectorAll('[data-city]').forEach(b=>b.onclick=()=>select(b.dataset.city));document.querySelector('.home-enter').onclick=enter;document.querySelector('.home-unfold').onclick=()=>select('overview');document.querySelector('.home-about').onclick=()=>shell.open('about');document.querySelector('.home-brand').onclick=e=>{e.preventDefault();select('theme');};document.querySelector('.home-retry').onclick=()=>select('overview');window.__home={diorama,shell,select,enter,get selected(){return selected;},get loading(){return loading;}};}catch(error){document.body.dataset.homeView='fallback';document.querySelector('.home-status').textContent='三维预览无法启动，仍可直接选择城镇。';document.querySelector('.home-enter').hidden=true;document.querySelector('.home-cities').innerHTML=CITIES.map(c=>`<a href="./aether.html?region=${c.id}&arrival=portal">${c.name}</a>`).join('');console.error(error);}
