import * as T from 'three';
import {createFerryArchitecture} from './ferry-architecture.js';
import {FERRY_STOPS,FERRY_LENGTH,FERRY_HULL,FERRY_MAST,ferryPose} from './ferry-route.js';
import './ferry.css';
export function createFerry(world,art,{nav,isBlocked,say,buildings}){
 const geometry=createFerryArchitecture(art,nav),{camera,controls}=world,canvas=world.renderer.domElement;
 let t=0,dock=0,target=1,state='docked',paused=false,following=false,speed=0,last=performance.now(),westAngle=1.2,foamClock=0,foamIndex=0,down=null,notice='';const foamParticles=[],ray=new T.Raycaster(),ndc=new T.Vector2(),lastBoat=new T.Vector3(),prior={};const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const panel=document.createElement('section');panel.className='ferry-panel';panel.hidden=true;panel.setAttribute('aria-label','晨露渡舟');panel.innerHTML='<header><strong>晨露渡舟</strong><button data-ferry="close" aria-label="离开随船视角">×</button></header><p class="ferry-route">前湾舟会 ⇄ 西岸林堤</p><p role="status"></p><progress max="1" value="0" aria-label="渡舟航程"></progress><div><button data-ferry="sail"></button><button data-ferry="pause">暂停航行</button><button data-ferry="shore">登岸观景</button></div><small>拖动环顾 · 滚轮缩放 · Esc 离开随船视角</small>';document.body.append(panel);
 const button=id=>panel.querySelector(`[data-ferry=${id}]`);
 const labels=FERRY_STOPS.map((stop,i)=>{const b=document.createElement('button');b.className='ferry-label';b.textContent=stop.name+' · 渡舟';b.hidden=true;b.onclick=()=>board();b.dataset.ferryDock=stop.id;document.body.append(b);return b;});
 const localMatrix=(pose)=>art.root.matrixWorld.clone().multiply(new T.Matrix4().makeTranslation(...pose.position.toArray())).multiply(new T.Matrix4().makeRotationY(pose.yaw));
 function clearAt(pose){art.root.updateWorldMatrix(true,false);const matrix=localMatrix(pose);return nav.clearVolume(matrix,FERRY_HULL,[art.boat,art.gangplank,geometry.westGang])&&nav.clearVolume(matrix,FERRY_MAST,[art.boat,art.gangplank,geometry.westGang]);}
 function refresh(){panel.dataset.state=state;panel.dataset.dock=FERRY_STOPS[dock].id;panel.dataset.following=String(following);panel.dataset.paused=String(paused);panel.querySelector('[role=status]').textContent=notice||(state==='docked'?FERRY_STOPS[dock].name+' · 已靠岸':state==='raising'?'收起两岸舷梯，准备离岸':state==='lowering'?'已停稳，正在放下舷梯':(paused?'暂泊水面 · ':'正在驶向 ')+FERRY_STOPS[target].name);panel.querySelector('progress').value=target===1?t:1-t;button('sail').textContent='启航至'+FERRY_STOPS[1-dock].name;button('sail').disabled=state!=='docked';button('pause').hidden=!['sailing'].includes(state);button('pause').textContent=paused?'继续航行':'暂停航行';button('shore').disabled=state!=='docked';}
 function unfollow(){if(following){following=false;controls.minDistance=prior.min;controls.maxDistance=prior.max;}panel.hidden=true;refresh();}
 function board(){if(isBlocked())return false;world.atlas?.travel('watercourt');buildings.close();world.cancelCameraMotion();prior.min=controls.minDistance;prior.max=controls.maxDistance;controls.minDistance=2;controls.maxDistance=40;following=true;panel.hidden=false;art.boat.updateWorldMatrix(true,true);const p=art.boat.getWorldPosition(new T.Vector3());camera.position.copy(p).add(innerWidth<700?new T.Vector3(10,11,18):new T.Vector3(8,6,10));controls.target.copy(p).y+=innerWidth<700?-1:1.2;controls.update();lastBoat.copy(p);refresh();return true;}
 function sail(){if(state!=='docked'||isBlocked())return false;target=1-dock;art.gangOpen=false;state='raising';paused=false;notice='';refresh();return true;}
 function toggleGang(){if(state!=='docked'||dock!==0){say('船只靠稳前湾后才能操作这座舷梯。');return false;}art.gangOpen=!art.gangOpen;return true;}
 function shore(){if(state!=='docked')return false;unfollow();world.cancelCameraMotion();const eye=dock?[-32,3,43]:[23,3.5,44],aim=dock?[-27,1,45]:[26,1,45];camera.position.copy(art.root.localToWorld(new T.Vector3(...eye)));controls.target.copy(art.root.localToWorld(new T.Vector3(...aim)));controls.update();return true;}
 button('close').onclick=unfollow;button('sail').onclick=sail;button('pause').onclick=()=>{paused=!paused;notice='';refresh();};button('shore').onclick=shore;
 const key=e=>{if(e.code==='Escape')unfollow();};window.addEventListener('keydown',key);
 const pd=e=>{if(e.button===0)down=[e.clientX,e.clientY];},release=()=>down=null,pu=e=>{const start=down;down=null;if(!start||e.button!==0||Math.hypot(e.clientX-start[0],e.clientY-start[1])>6||isBlocked())return;const r=canvas.getBoundingClientRect();ndc.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(ndc,camera);ray.far=65;const hits=ray.intersectObject(art.root,true).filter(h=>h.object.visible);if(!hits.length)return;const h=hits[0];let o=h.object;while(o&&!o.userData.ferryAction)o=o.parent;if(o&&!nav.obstructed(camera.position,h.point.clone().lerp(camera.position,.03),.005))board();};canvas.addEventListener('pointerdown',pd);canvas.addEventListener('pointerup',pu);canvas.addEventListener('pointercancel',release);window.addEventListener('blur',release);
 function update(){const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;
  if(following&&(document.querySelector('dialog[open]')||buildings.selected||document.body.dataset.visitorHidden==='true'))unfollow();
  if(state==='raising'&&art.gangAngle>1.18&&westAngle>1.18)state='sailing';
  if(state==='sailing'&&!paused&&!document.hidden){const remaining=Math.abs(target-t)*FERRY_LENGTH;speed=T.MathUtils.damp(speed,Math.min(2.8,.25+remaining*1.4),2,dt);const next=T.MathUtils.clamp(t+(target?1:-1)*speed*dt/FERRY_LENGTH,0,1),pose=ferryPose(next);if(clearAt(pose)){t=next;art.boat.position.copy(pose.position);art.boat.rotation.y=pose.yaw;}else{paused=true;speed=0;notice='前方有障碍，船已停下；清除后可继续。';}if(t===target){dock=target;state='lowering';speed=0;art.gangOpen=dock===0;}}
  else speed=0;
  westAngle=T.MathUtils.damp(westAngle,(state==='lowering'||state==='docked')&&dock===1?-.337:1.2,5,dt);geometry.westGang.rotation.z=westAngle;
  if(state==='lowering'&&Math.abs((dock?westAngle:art.gangAngle)+.337)<.008){state='docked';notice='';say('晨露渡舟已靠岸：'+FERRY_STOPS[dock].name);}
  const p=art.boat.getWorldPosition(new T.Vector3());if(following){const delta=p.clone().sub(lastBoat);camera.position.add(delta);controls.target.add(delta);}lastBoat.copy(p);
  foamClock+=dt;if(speed>.1&&!reduced.matches&&foamClock>.09){foamClock=0;const pose=ferryPose(t),dir=new T.Vector3(Math.sin(pose.yaw),0,Math.cos(pose.yaw)).multiplyScalar(target?1:-1),side=new T.Vector3(dir.z,0,-dir.x);for(const s of [-1,1])foamParticles[foamIndex++%100]={age:0,pos:pose.position.clone().addScaledVector(dir,-3.4).addScaledVector(side,s*.62),side:side.clone().multiplyScalar(s),yaw:pose.yaw};}
  for(let i=0;i<100;i++){const particle=foamParticles[i],d=geometry.dummy;if(particle&&!reduced.matches&&(particle.age+=dt)<4){d.position.copy(particle.pos).addScaledVector(particle.side,particle.age*.24);d.position.y=.025;d.rotation.set(-Math.PI/2,0,-particle.yaw);d.scale.setScalar((1-particle.age/4)*(.7+particle.age*.3));}else d.scale.setScalar(0);d.updateMatrix();geometry.foam.setMatrixAt(i,d.matrix);}geometry.foam.instanceMatrix.needsUpdate=true;
  for(const[i,b]of labels.entries()){const v=art.root.localToWorld(new T.Vector3(i?-30:23,2.7,45)),distance=camera.position.distanceTo(v);v.project(camera);b.hidden=following||isBlocked()||document.body.dataset.visitorHidden==='true'||distance>60||v.z<-1||v.z>1||Math.abs(v.x)>.85||Math.abs(v.y)>.7;if(!b.hidden){b.style.left=(v.x*.5+.5)*innerWidth+'px';b.style.top=(-v.y*.5+.5)*innerHeight+'px';}}
  refresh();
 }
 refresh();return{geometry,board,sail,shore,unfollow,toggleGang,update,clearAt,get following(){return following;},stats:()=>({state,t,dock:FERRY_STOPS[dock].id,target:FERRY_STOPS[target].id,paused,following,speed,position:art.boat.position.toArray(),yaw:art.boat.rotation.y,westAngle,routeLength:FERRY_LENGTH}),dispose(){unfollow();geometry.dispose();panel.remove();labels.forEach(b=>b.remove());window.removeEventListener('keydown',key);window.removeEventListener('blur',release);canvas.removeEventListener('pointerdown',pd);canvas.removeEventListener('pointerup',pu);canvas.removeEventListener('pointercancel',release);}};
}
