import {cameraInputEnabled,restoreCameraInput} from './camera-input.js';
import * as T from 'three';
import {createForestGardenArchitecture} from './forest-garden-architecture.js';
import {GARDEN_BEDS,GARDEN_CROPS} from './forest-garden-content.js';
import {GOODS,MARKET_KEY} from './market-content.js';
import './forest-garden.css';
export function createForestGarden(world,{settlements,nav,buildings,gathering,market,town,isBlocked,say}){
 const {camera,controls,renderer}=world,canvas=renderer.domElement,reduced=matchMedia('(prefers-reduced-motion: reduce)'),ray=new T.Raycaster(),pointer=new T.Vector2(),removers=[];let art=null,selected=null,room=0,down=null,enabled=true,previous=null,disposed=false,pending=false,view='',bedId=null,shade=false,shadeAngle=0,last=performance.now(),scanned=0,state=market.store.snapshot().garden;
 const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;},button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;},name=id=>GOODS.find(g=>g.id===id)?.name||id;
 const dialog=el('dialog');dialog.className='fgarden-dialog';dialog.setAttribute('aria-labelledby','fgarden-title');dialog.innerHTML='<header><div><small>紫境 · 月桂园</small><h2 id="fgarden-title"></h2></div><button aria-label="关闭月桂园手册">×</button></header><div class="fgarden-body"></div><p role="status" aria-live="polite"></p>';
 const panel=el('section');panel.className='fgarden-panel';panel.hidden=true;panel.innerHTML='<header><strong></strong><button aria-label="退出月桂园近观">×</button></header><nav></nav><div class="fgarden-actions"></div><p role="status"></p>';
 const hint=button('月桂园 · 温室与药草馆',directory);hint.className='fgarden-hint';hint.hidden=true;document.body.append(dialog,panel,hint);
 function close(){if(dialog.open)dialog.close();}dialog.querySelector('header button').onclick=close;dialog.addEventListener('close',()=>{if(!document.querySelector('dialog[open]')&&!world.atlas.town.busy)restoreCameraInput(world,enabled);(previous?.isConnected?previous:canvas).focus({preventScroll:true});});
 function show(title,kind){world.atlas.resources.cancel();town.clear();gathering.cancel({clearSelection:true});world.cancelCameraMotion();view=kind;dialog.dataset.view=kind;dialog.querySelector('h2').textContent=title;dialog.querySelector('.fgarden-body').replaceChildren();dialog.querySelector('[role=status]').textContent='';if(!dialog.open){enabled=cameraInputEnabled(world);previous=document.activeElement;controls.enabled=false;dialog.showModal();}dialog.querySelector('header button').focus();}
 const handoff=fn=>{dialog.addEventListener('close',fn,{once:true});close();};
 function directory(){if(!art||isBlocked())return false;show('月桂园','directory');const body=dialog.querySelector('.fgarden-body');body.append(el('p','沿主林道向东，玻璃拱顶下有六张苗床，叶瓦小馆里保存着种子与标本。'));for(const r of art.records){const card=el('article');card.append(el('h3',r.name),el('p',r.def.rooms.join(' · ')),button('看建筑外观',()=>handoff(()=>focus(r.type,-1))));r.def.rooms.forEach((n,i)=>card.append(button('进入'+n,()=>handoff(()=>focus(r.type,i)))));body.append(card);}body.append(button('看林间庭院',()=>handoff(overview)));return true;}
 function focus(id,index=0){if(!art||isBlocked())return false;const r=art.records.find(r=>r.type===id);if(!r||index>=r.rooms.length)return false;world.atlas.travel('forest');selected=r;room=index;if(index>=0){r.interior=r.rooms[index].eye;r.target=r.rooms[index].target;if(index===1){const d=r.doors[1];d.open=true;d.angle=-1.48;d.root.rotation.y=-1.48;}}const ok=buildings.focus(r,index>=0,{lightScale:.25});renderPanel();return ok;}
 function overview(){if(!art||isBlocked())return false;world.atlas.travel('forest');world.cancelCameraMotion();camera.position.copy(art.root.localToWorld(new T.Vector3(14,art.floor+14,24)));controls.target.copy(art.root.localToWorld(new T.Vector3(-2,art.floor+3,-2)));camera.lookAt(controls.target);controls.update();return true;}
 function renderPanel(){panel.hidden=!selected;if(!selected)return;panel.dataset.building=selected.type;panel.dataset.room=String(room);panel.querySelector('strong').textContent=selected.name;const n=panel.querySelector('nav'),actions=panel.querySelector('.fgarden-actions');n.replaceChildren();actions.replaceChildren();for(const [i,label]of [[-1,'外观'],...selected.def.rooms.map((n,i)=>[i,n])]){const b=button(label,()=>focus(selected.type,i));b.dataset.room=String(i);b.setAttribute('aria-pressed',String(i===room));n.append(b);}selected.doors.forEach((d,i)=>{const b=button((d.open?'关闭':'打开')+(i?'内门':'正门'),()=>{d.open=!d.open;renderPanel();});b.dataset.gardenDoor=String(i);b.setAttribute('aria-pressed',String(d.open));actions.append(b);});actions.append(button(selected.lampsOn?'熄下吊灯':'点亮吊灯',()=>{selected.lampsOn=!selected.lampsOn;renderPanel();}));if(selected.type==='glasshouse'){const b=button(shade?'合上遮阳翼':'展开遮阳翼',()=>{shade=!shade;renderPanel();});b.dataset.gardenShade='true';actions.append(b);for(let i=0;i<GARDEN_BEDS.length;i++){const b=button('查看苗床 '+(i+1),()=>bed(GARDEN_BEDS[i]));b.dataset.bed=GARDEN_BEDS[i];actions.append(b);}}else actions.append(button('到拣种与研磨台',()=>town.focus('seed-table')),button('翻开栽培标本册',book));panel.querySelector('p').textContent='拖动环顾 · 点击苗床、门扇或标本册也可互动';}
 async function transact(fn,render){if(pending)return;pending=true;let result;try{const run=()=>{if(disposed)return null;market.store.reload();return fn();};result=navigator.locks?await navigator.locks.request(MARKET_KEY,run):run();}catch{result={ok:false,message:'保存未完成，请重试。'};}pending=false;if(disposed)return;state=market.store.snapshot().garden;scanned=0;gathering.refreshBag();if(dialog.open){render();dialog.querySelector('[role=status]').textContent=result?.message||'操作已取消。';}}
 function bed(id){if(!art||!GARDEN_BEDS.includes(id))return;bedId=id;if(!dialog.open){const r=art.records[0],b=art.beds.find(b=>b.id===id);world.cancelCameraMotion();camera.position.copy(r.root.localToWorld(new T.Vector3(0,2.4,b.root.position.z+1.25)));controls.target.copy(b.root.localToWorld(new T.Vector3(0,1.0,0)));camera.lookAt(controls.target);controls.update();}show('苗床 '+(GARDEN_BEDS.indexOf(id)+1),'bed');dialog.dataset.bed=id;const body=dialog.querySelector('.fgarden-body'),s=market.store.snapshot(),planted=s.garden.beds[id];if(planted){const crop=GARDEN_CROPS.find(c=>c.id===planted.crop);body.append(el('h3',crop.name),el('p',crop.text));const count=el('p');count.dataset.growth='true';body.append(count);const harvest=button('采收成熟植物',()=>transact(()=>market.store.harvestGarden(id),()=>bed(id)));harvest.dataset.gardenHarvest='true';body.append(harvest);refreshCountdown();}else{body.append(el('p','每次播种消耗一包种子与一罐净水。浇水后自动生长，成熟后不会枯萎，可以稍后回来采收。'));for(const crop of GARDEN_CROPS){const row=el('article');row.dataset.crop=crop.id;row.append(el('h3',crop.name),el('p',crop.text),el('p',name(crop.seed)+' × 1 · 行囊 '+s.bag[crop.seed]+'；净水 × 1 · 行囊 '+s.bag.water),el('p','生长 '+crop.duration/1000+' 秒 · 收获 '+Object.entries(crop.yield).map(([id,n])=>name(id)+' × '+n).join('、')));const b=button('播种并浇水',()=>transact(()=>market.store.plantGarden(id,crop.id),()=>bed(id)));b.dataset.gardenPlant=crop.id;b.disabled=!s.bag[crop.seed]||!s.bag.water;row.append(b);body.append(row);}}body.append(button('到工坊拣选种子',()=>handoff(()=>town.focus('seed-table'))),button('寻找水与原料',()=>handoff(()=>world.atlas.resources.showDirectory())));}
 function refreshCountdown(){if(!dialog.open||view!=='bed')return;const b=market.store.snapshot().garden.beds[bedId],text=dialog.querySelector('[data-growth]'),button=dialog.querySelector('[data-garden-harvest]');if(!b||!text)return;const remaining=Math.max(0,Math.ceil((b.readyAt-Date.now())/1000));text.textContent=remaining?'正在生长 · 约 '+remaining+' 秒后成熟':'已经成熟，可以采收。';button.disabled=remaining>0;}
 function book(){show('月桂园 · 栽培标本册','book');const body=dialog.querySelector('.fgarden-body'),s=market.store.snapshot().garden;body.append(el('p','收获记录 '+s.harvested+' 次 · 两种栽培标本 '+s.seen.length+' / 2'));for(const crop of GARDEN_CROPS){const row=el('article');row.append(el('h3',crop.name+' · '+(s.seen.includes(crop.id)?'已栽培收录':'尚未收录')),el('p',crop.text));body.append(row);}const reward=button(s.reward?'月桂盆栽已经领取':'领取栽培纪念盆栽',()=>transact(()=>market.store.claimGarden(),book));reward.dataset.gardenReward='true';reward.disabled=s.reward||s.seen.length!==GARDEN_CROPS.length;body.append(reward,el('p','各收获一次月桂与山麦后，可领取一盆月桂，摆进山城旅人客房。'));}
 function add(region,source){if(region.id!=='forest'||art)return;art=createForestGardenArchitecture(settlements,source);for(const r of art.records){r.doors.forEach(d=>removers.push(nav.addDynamic(d.proxy)));if(r.bench)town.registerWorkshop({id:'seed-table',profession:'forest',recipeIds:['moon-seeds','wheat-seeds','extract','tonic'],name:'月桂拣种与研磨台',building:r,prop:r.bench});}const link=button('月桂园',()=>{const map=document.querySelector('.atlas-map');if(map.open){map.addEventListener('close',directory,{once:true});map.close();}else directory();});link.dataset.forestGarden='true';document.querySelector('[data-region-card=forest]>div:last-child')?.append(link);removers.push(()=>link.remove());}
 function reserveFlora(region){if(region.id==='forest'&&art)removers.push(gathering.flora.reserveWhere(p=>p.y<art.floor+1&&art.clearAt(p.x-art.center[0],p.z-art.center[2])));}
 function clear(){selected=null;down=null;panel.hidden=true;hint.hidden=true;close();}panel.querySelector('header button').onclick=()=>{clear();buildings.close();};const ancestor=(o,r)=>{for(;o;o=o.parent)if(o===r)return true;return false;};
 function pointerUp(e){const start=down;down=null;if(!start||e.button!==0||Math.hypot(e.clientX-start[0],e.clientY-start[1])>6||!art||isBlocked()||document.body.dataset.visitorHidden==='true')return;const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);ray.far=65;const hit=ray.intersectObject(art.root,true).find(h=>{for(let p=h.object;p;p=p.parent)if(!p.visible)return false;return true;});if(!hit)return;const r=art.records.find(r=>ancestor(hit.object,r.root));if(!r||r.bench&&ancestor(hit.object,r.bench.root))return;const di=r.doors.findIndex(d=>ancestor(hit.object,d.root));if(nav.obstructed(camera.position,hit.point.clone().lerp(camera.position,.02),.005,null,di>=0?r.doors[di].proxy:null))return;if(hit.distance>12){queueMicrotask(()=>focus(r.type,-1));return;}if(di>=0){r.doors[di].open=!r.doors[di].open;if(selected===r)renderPanel();return;}for(let o=hit.object;o;o=o.parent){if(o.userData.gardenBed){bed(o.userData.gardenBed);return;}if(o.userData.gardenAction==='book'){book();return;}if(o.userData.gardenAction==='lamps'){r.lampsOn=!r.lampsOn;renderPanel();return;}}if(buildings.selected!==r.id)queueMicrotask(()=>focus(r.type,-1));}
 const pd=e=>{if(e.button===0)down=[e.clientX,e.clientY];},release=()=>down=null,key=e=>{if(e.code==='Escape'&&!dialog.open)clear();},storage=e=>{if(e.key!==MARKET_KEY)return;market.store.reload();scanned=0;if(dialog.open){if(view==='bed')bed(bedId);else if(view==='book')book();}};canvas.addEventListener('pointerdown',pd);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',release);window.addEventListener('blur',release);window.addEventListener('keydown',key);window.addEventListener('storage',storage);
 function update(){if(!art)return;const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;shadeAngle=reduced.matches?(shade?1.0:0):T.MathUtils.damp(shadeAngle,shade?1.0:0,6,dt);for(const v of art.vents)v.root.rotation.z=v.side*shadeAngle;for(const r of art.records){for(const d of r.doors){d.angle=reduced.matches?(d.open?-1.48:0):T.MathUtils.damp(d.angle,d.open?-1.48:0,7,dt);d.root.rotation.y=d.angle;}const near=camera.position.distanceTo(r.root.getWorldPosition(new T.Vector3()))<35;r.lamps.forEach(l=>l.intensity=near&&r.lampsOn?12:0);r.filament.emissiveIntensity=r.lampsOn?.35:0;}
 if(now-scanned>350){scanned=now;state=market.store.snapshot().garden;const clock=Date.now();for(const p of art.plants){const b=state.beds[p.bed];p.root.visible=b?.crop===p.crop;if(p.root.visible){const t=T.MathUtils.clamp((clock-b.plantedAt)/(b.readyAt-b.plantedAt),0,1);p.root.scale.setScalar(.12+.88*t);}}refreshCountdown();}
 if(buildings.selected&&buildings.selected!==selected?.id){const r=art.records.find(r=>r.id===buildings.selected);selected=r||null;if(r){room=buildings.inside?Math.max(0,room):-1;renderPanel();}else panel.hidden=true;}if(selected&&!buildings.selected){selected=null;panel.hidden=true;}if(isBlocked()||selected||document.body.dataset.visitorHidden==='true'){hint.hidden=true;return;}const p=art.root.localToWorld(new T.Vector3(-1,art.floor+5,4)),v=p.clone().project(camera);hint.hidden=p.distanceTo(camera.position)>80||v.z< -1||v.z>1||Math.abs(v.x)>.8||Math.abs(v.y)>.8;if(!hint.hidden){hint.style.left=T.MathUtils.clamp((v.x*.5+.5)*innerWidth,120,innerWidth-120)+'px';hint.style.top=T.MathUtils.clamp((-v.y*.5+.5)*innerHeight,130,innerHeight-260)+'px';}}
 return{add,reserveFlora,update,clear,directory,focus,overview,bed,book,get architecture(){return art;},stats:()=>({selected:selected?.type,room,shade,shadeAngle,state:market.store.snapshot().garden,floor:art?.floor,removed:art?.removed,plants:art?.plants.map(p=>({bed:p.bed,crop:p.crop,visible:p.root.visible,scale:p.root.scale.y}))}),dispose(){disposed=true;clear();removers.forEach(fn=>fn());art?.dispose();[dialog,panel,hint].forEach(n=>n.remove());canvas.removeEventListener('pointerdown',pd);canvas.removeEventListener('pointerup',pointerUp);canvas.removeEventListener('pointercancel',release);window.removeEventListener('blur',release);window.removeEventListener('keydown',key);window.removeEventListener('storage',storage);}};
}
