import * as T from 'three';
import {FURNITURE,HOME_COLORS,HOME_LIMIT} from './housing-content.js';
import {MARKET_KEY} from './market-content.js';
import {makeFurniture} from './housing-props.js';
import './housing.css';
export function createHousing(world,{settlements,market,nav,buildings,gathering,isBlocked,say}){
 const {camera,controls,renderer}=world,canvas=renderer.domElement,store=market.store,room=settlements.records.find(r=>r.name==='山城木屋 01'),objects=new Map(),ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(),point=new T.Vector3();let editing=false,selection=null,drag=null,oldEnabled=true,lastMove=0;
 const panel=document.createElement('section');panel.className='home-editor';panel.hidden=true;panel.setAttribute('aria-label','旅人客房布置');panel.innerHTML='<header><small>牛角山城 · 一号木屋</small><button data-close aria-label="结束客房布置">完成</button><h2>旅人客房</h2></header><p class="home-help">选择陈设后拖动。R 旋转，方向键微调，Esc 退出。门口保留通道。</p><button data-overview>查看全屋</button><div class="home-catalog"></div><details class="home-existing"><summary>房间里的陈设</summary><div></div></details><div class="home-selection"></div><p class="home-status" role="status" aria-live="polite"></p>';
 const entry=document.createElement('button');entry.className='home-entry';entry.textContent='布置旅人客房';entry.hidden=true;document.body.append(panel,entry);const catalog=panel.querySelector('.home-catalog'),info=panel.querySelector('.home-selection'),status=panel.querySelector('.home-status');
 const outline=new T.BoxHelper(new T.Object3D(),0xe5cb8d);outline.visible=false;outline.material.depthTest=false;outline.renderOrder=100;outline.userData.noCollision=true;world.scene.add(outline);
 const el=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;},button=(text,fn,disabled=false)=>{const b=el('button',text);b.type='button';b.onclick=fn;b.disabled=disabled;return b;};
 function feedback(r){status.textContent=r.message+(r.ok&&!r.saved?' 当前无法写入存档，刷新后可能丢失。':'');gathering.refreshBag();}
 function local(x,y,z){return room.root.localToWorld(new T.Vector3(x,y,z));}
 function apply(record,item){record.item=structuredClone(item);record.prop.root.position.set(item.x,record.y||.06,item.z);record.prop.root.rotation.y=item.yaw;record.prop.style(item);record.prop.root.updateWorldMatrix(true,true);}
 function cornersOf(x,z,w,d,yaw=0){const c=Math.cos(yaw),s=Math.sin(yaw);return[[-w/2,-d/2],[w/2,-d/2],[w/2,d/2],[-w/2,d/2]].map(([a,b])=>[x+a*c+b*s,z-a*s+b*c]);}
 function overlaps(a,b){for(const polygon of [a,b])for(let i=0;i<4;i++){const p=polygon[i],q=polygon[(i+1)%4],axis=[q[1]-p[1],p[0]-q[0]],aa=a.map(v=>v[0]*axis[0]+v[1]*axis[1]),bb=b.map(v=>v[0]*axis[0]+v[1]*axis[1]);if(Math.max(...aa)<Math.min(...bb)+.015||Math.max(...bb)<Math.min(...aa)+.015)return false;}return true;}
 function placement(record,pos){if(![pos.x,pos.z,pos.yaw].every(Number.isFinite))return{ok:false,message:'无效位置。'};const [w,h,d]=record.prop.def.size,ca=Math.cos(pos.yaw),sa=Math.sin(pos.yaw),corners=[[-w/2,-d/2],[w/2,-d/2],[w/2,d/2],[-w/2,d/2],[0,0]].map(([x,z])=>[pos.x+x*ca+z*sa,pos.z-x*sa+z*ca]);if(corners.some(([x,z])=>Math.abs(x)>3.5||Math.abs(z)>5.4))return{ok:false,message:'请把陈设留在房间内。'};if(record.item.kind!=='rug'&&corners.some(([x,z])=>Math.abs(x)<.75&&z>3.1))return{ok:false,message:'请给门口留出通道。'};
  const polygon=corners.slice(0,4);for(const o of room.roomObstacles||[]){if(record.item.kind!=='rug'&&overlaps(polygon,cornersOf(...o)))return{ok:false,message:'与房间原有家具重叠。'};}for(const other of objects.values()){if(other===record||(record.item.kind==='rug')!==(other.item.kind==='rug'))continue;const [ow,,od]=other.prop.def.size;if(overlaps(polygon,cornersOf(other.item.x,other.item.z,ow,od,other.item.yaw)))return{ok:false,message:'与其他陈设重叠。'};}
  room.root.updateWorldMatrix(true,false);const base=room.root.getWorldPosition(new T.Vector3()).y,heights=corners.map(([x,z])=>{const p=local(x,0,z);return nav.height(p.x,p.z,base+.24,base-.20);});if(heights.some(y=>y===null)||Math.max(...heights)-Math.min(...heights)>.035)return{ok:false,message:'这里没有平整地面。'};const ground=Math.max(...heights),y=ground-base+.008;
  // Grid of vertical capsules tests the actual static triangle mesh and other
  // dynamic furniture. Own proxy is ignored only for its move preview.
  for(let x=-w/2+.05;x<=w/2;x+=Math.min(.18,w/3))for(let z=-d/2+.05;z<=d/2;z+=Math.min(.18,d/3)){const xx=pos.x+x*ca+z*sa,zz=pos.z-x*sa+z*ca,from=local(xx,y+Math.min(.13,h*.6),zz),to=local(xx,y+Math.max(.13,h-.07),zz);if(nav.obstructed(from,to,record.item.kind==='rug'?.012:.065,null,record.item.kind==='rug'?true:record.prop.proxy))return{ok:false,message:'与墙体、固定家具或其他陈设重叠。'};}
  return{ok:true,y,message:'可以摆放。'};
 }
 function sync(){const items=store.snapshot().home.objects;for(const[id,r]of objects)if(!items.some(o=>o.id===id)){r.remove();r.prop.dispose();objects.delete(id);}for(const item of items){let r=objects.get(item.id);if(!r){const prop=makeFurniture(room.root,settlements.materials,item);r={item,prop,y:.06,remove:item.kind==='rug'?()=>{}:nav.addDynamic(prop.proxy)};objects.set(item.id,r);}apply(r,item);}for(const r of objects.values()){const check=placement(r,r.item);r.invalid=check.ok?null:check.message;if(check.ok){r.y=check.y;apply(r,r.item);}}if(selection&&!objects.has(selection))selection=null;}
 function focusSelection(){if(!editing)return;if(innerWidth>=700){camera.clearViewOffset();return;}camera.setViewOffset(innerWidth,innerHeight,0,innerHeight*.16,innerWidth,innerHeight);const r=objects.get(selection);if(r){camera.position.copy(local(T.MathUtils.clamp(r.item.x,-2.7,2.7),3.6,5.5));controls.target.copy(local(r.item.x,r.y+r.prop.def.size[1]*.35,r.item.z));}else{camera.position.copy(local(-.15,4.05,5.5));controls.target.copy(local(-.25,.25,1.5));}camera.lookAt(controls.target);controls.update();}
 function choose(id){selection=id;render();mark();focusSelection();}
 function mark(valid=true){const r=objects.get(selection);outline.visible=editing&&!!r;if(r){outline.setFromObject(r.prop.root);outline.material.color.set(valid?'#e5cb8d':'#e77a65');}}
 function render(){const state=store.snapshot();catalog.replaceChildren();for(const f of FURNITURE)catalog.append(button(`${f.name} · ${state.bag[f.id]||0}`,()=>add(f.id),!state.bag[f.id]||objects.size>=HOME_LIMIT));const list=panel.querySelector('.home-existing>div');list.replaceChildren();for(const r of objects.values())list.append(button(r.prop.def.name+' #'+r.item.id,()=>choose(r.item.id)));info.replaceChildren();const r=objects.get(selection);if(!r){info.append(el('p','从行囊选择一件陈设，或点选房间里的物件。'));return;}info.append(el('h3',r.prop.def.name),el('small','按 15° 旋转 · 每次微调 10 cm'));const move=el('div','');move.className='home-move';move.append(button('←',()=>nudge(-.1,0)),button('↑',()=>nudge(0,-.1)),button('↓',()=>nudge(0,.1)),button('→',()=>nudge(.1,0)),button('↶ 15°',()=>rotate(-1)),button('↷ 15°',()=>rotate(1)));info.append(move);const colors=el('div','');colors.className='home-colors';for(const c of HOME_COLORS){const b=button(c.name,()=>{feedback(store.styleHome(r.item.id,c.id));sync();render();mark();});b.style.setProperty('--swatch',c.color);b.setAttribute('aria-pressed',String(r.item.color===c.id));colors.append(b);}info.append(colors);if(r.item.kind==='lantern')info.append(button(r.item.lit?'熄灭旅行灯':'点亮旅行灯',()=>{feedback(store.lightHome(r.item.id));sync();render();}));info.append(button('收回行囊',()=>{feedback(store.retrieve(r.item.id));sync();render();mark();}));}
 function findPlace(r){for(const [x,z]of [[-2.2,3.6],[-1.2,3.3],[1.4,1.7],[-2.4,1.6],[.9,.8],[-.6,1],[-2.5,4.6],[1.5,4.5],[-1.6,-4.3]]){const pos={x,z,yaw:0},check=placement(r,pos);if(check.ok)return{pos,check};}for(let z=4.6;z>=-4.6;z-=.5)for(let x=-2.8;x<=2.8;x+=.5){const pos={x,z,yaw:0},check=placement(r,pos);if(check.ok)return{pos,check};}return null;}
 function add(kind){if(!editing)return;const dummy={id:-1,kind,x:0,z:0,yaw:0,color:'ochre',lit:true},prop=makeFurniture(room.root,settlements.materials,dummy),temp={prop,item:dummy},found=findPlace(temp);prop.dispose();if(!found){status.textContent='房间里暂时没有足够空位，请收回或移动一些陈设。';return;}const result=store.place(kind,found.pos);feedback(result);sync();if(result.ok)selection=result.item.id;render();mark();focusSelection();}
 function moveTo(pos,commit=true){const r=objects.get(selection);if(!r)return false;const check=placement(r,pos);if(!check.ok){status.textContent=check.message;mark(false);return false;}r.y=check.y;apply(r,{...r.item,...pos});mark();if(commit){feedback(store.moveHome(r.item.id,pos));sync();}return true;}
 function nudge(dx,dz){const r=objects.get(selection);if(r)moveTo({x:r.item.x+dx,z:r.item.z+dz,yaw:r.item.yaw});}
 function rotate(dir){const r=objects.get(selection);if(r)moveTo({x:r.item.x,z:r.item.z,yaw:r.item.yaw+dir*Math.PI/12});}
 function close(){if(!editing)return;cancelDrag();editing=false;panel.hidden=true;outline.visible=false;delete document.body.dataset.homeEditing;camera.clearViewOffset();controls.enabled=oldEnabled;canvas.focus({preventScroll:true});}
 function open(){if(isBlocked())return false;world.atlas.travel('highland');world.cancelCameraMotion();gathering.cancel({clearSelection:true});buildings.focus(room,true,{lightScale:.65});const firstVisit=!store.snapshot().home.claimed;if(firstVisit)feedback(store.claimHome());sync();oldEnabled=controls.enabled;editing=true;controls.enabled=false;document.body.dataset.homeEditing='true';panel.hidden=false;entry.hidden=true;camera.position.copy(local(-.15,4.05,5.5));controls.target.copy(local(-.25,.25,1.5));camera.lookAt(controls.target);controls.update();render();focusSelection();panel.querySelector('.home-help').textContent=innerWidth<700?'选择物件后拖动，或用方向按钮微调。门口保留通道。':'选择陈设后拖动。R 旋转，方向键微调，Esc 退出。门口保留通道。';status.textContent=firstVisit?'五件基础陈设已备好。拖动摆放，位置会自动保存。':'已恢复客房陈设。可以继续添置、移动或收回物件。';panel.querySelector('[data-close]').focus();return true;}
 function setRay(e){const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);}
 function down(e){if(!editing||e.button!==0)return;setRay(e);let best=null;for(const r of objects.values()){const hit=ray.intersectObject(r.prop.root,true).find(h=>h.object.visible);if(hit&&(!best||hit.distance<best.hit.distance))best={r,hit};}if(!best)return;choose(best.r.item.id);plane.set(new T.Vector3(0,1,0),-local(0,.1,0).y);if(!ray.ray.intersectPlane(plane,point))return;const p=room.root.worldToLocal(point.clone());drag={id:e.pointerId,item:structuredClone(best.r.item),offset:[best.r.item.x-p.x,best.r.item.z-p.z],moved:false};canvas.setPointerCapture(e.pointerId);}
 function move(e){if(!drag||e.pointerId!==drag.id||performance.now()-lastMove<30)return;lastMove=performance.now();setRay(e);plane.set(new T.Vector3(0,1,0),-local(0,.1,0).y);if(!ray.ray.intersectPlane(plane,point))return;const p=room.root.worldToLocal(point.clone()),r=objects.get(selection);const pos={x:Math.round((p.x+drag.offset[0])*10)/10,z:Math.round((p.z+drag.offset[1])*10)/10,yaw:r.item.yaw};drag.moved=moveTo(pos,false)||drag.moved;}
 function up(e){if(!drag||e.pointerId!==drag.id)return;const old=drag;drag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);const r=objects.get(selection);if(old.moved&&r){feedback(store.moveHome(r.item.id,{x:r.item.x,z:r.item.z,yaw:r.item.yaw}));sync();}mark();}
 function cancelDrag(){if(!drag)return;const old=drag;drag=null;const r=objects.get(selection);if(r){const check=placement(r,old.item);if(check.ok)r.y=check.y;apply(r,old.item);}if(canvas.hasPointerCapture(old.id))canvas.releasePointerCapture(old.id);mark();}
 const key=e=>{if(!editing||e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(drag)cancelDrag();else close();return;}if(e.repeat||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const moves={ArrowLeft:[-.1,0],ArrowRight:[.1,0],ArrowUp:[0,-.1],ArrowDown:[0,.1]};if(moves[e.code]||e.code==='KeyR'){e.preventDefault();e.stopImmediatePropagation();if(e.code==='KeyR')rotate(e.shiftKey?-1:1);else nudge(...moves[e.code]);}};
 const resize=()=>{if(editing){cancelDrag();requestAnimationFrame(focusSelection);}},blur=()=>cancelDrag(),storage=e=>{if(e.key!==MARKET_KEY)return;cancelDrag();store.reload();sync();if(editing){render();mark();}gathering.refreshBag();};panel.querySelector('[data-overview]').onclick=()=>choose(null);panel.querySelector('[data-close]').onclick=close;entry.onclick=open;canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancelDrag);window.addEventListener('keydown',key,true);window.addEventListener('blur',blur);window.addEventListener('resize',resize);window.addEventListener('storage',storage);sync();
 function update(){if(editing&&buildings.selected!==room.id){close();return;}entry.hidden=editing||isBlocked()||buildings.selected!==room.id||!buildings.inside;const lights=[...objects.values()].filter(r=>r.prop.light&&r.item.lit).sort((a,b)=>a.prop.root.getWorldPosition(new T.Vector3()).distanceToSquared(camera.position)-b.prop.root.getWorldPosition(new T.Vector3()).distanceToSquared(camera.position));for(const r of objects.values())if(r.prop.light)r.prop.light.intensity=lights.indexOf(r)>=0&&lights.indexOf(r)<3?7:0;}
 return{open,close,update,store,room,objects,sync,placement,get editing(){return editing;},get fov(){return innerWidth<700&&!selection?110:74;},stats:()=>({editing,selection,objects:[...objects.values()].map(r=>({item:r.item,y:r.y,valid:placement(r,r.item)}))}),dispose(){close();for(const r of objects.values()){r.remove();r.prop.dispose();}outline.geometry.dispose();outline.material.dispose();outline.removeFromParent();panel.remove();entry.remove();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancelDrag);window.removeEventListener('keydown',key,true);window.removeEventListener('blur',blur);window.removeEventListener('resize',resize);window.removeEventListener('storage',storage);}};
}
