import {cameraInputEnabled,restoreCameraInput} from './camera-input.js';
import * as T from 'three';
import {createMarketArchitecture} from './market-architecture.js';
import {createMarketStore} from './market-store.js';
import {GOODS,MARKET_KEY,DELIVERY_REGIONS} from './market-content.js';
import {TRADES} from './town-content.js';
import './market.css';
export function createMarket(world,{settlements,source,nav,buildings,gathering,isBlocked,say}){
 const architecture=createMarketArchitecture(settlements,source),records=architecture.records,store=createMarketStore(),canvas=world.renderer.domElement,{camera,controls}=world,ray=new T.Raycaster(),ndc=new T.Vector2();nav.add(architecture.root);for(const r of records)nav.add(r.root);const removeDynamic=records.map(r=>nav.addDynamic(r.proxy));for(const r of records)r.onEnter=()=>{r.open=true;r.angle=-1.48;r.door.rotation.y=r.angle;};
 let selected=null,down=null,previous=null,enabled=true,view='directory',last=performance.now();const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const dialog=document.createElement('dialog');dialog.className='market-dialog';dialog.setAttribute('aria-labelledby','market-title');dialog.innerHTML='<header><small>牛角山城 · 集市街</small><button aria-label="关闭市集">×</button><h2 id="market-title"></h2><p class="market-balance"></p></header><div class="market-body"></div><p class="market-feedback" role="status"></p>';
 const hint=document.createElement('button');hint.className='market-hint';hint.hidden=true;document.body.append(dialog,hint);const body=dialog.querySelector('.market-body'),feedback=dialog.querySelector('.market-feedback');
 const el=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;},button=(label,fn,disabled=false)=>{const b=el('button',label);b.type='button';b.onclick=fn;b.disabled=disabled;return b;};
 function close(){dialog.close();}function handoff(fn){dialog.addEventListener('close',fn,{once:true});close();}dialog.querySelector('header button').onclick=close;dialog.addEventListener('close',()=>{if(!document.querySelector('dialog[open]')&&!document.body.dataset.townBusy)restoreCameraInput(world,enabled);(previous?.isConnected?previous:canvas).focus({preventScroll:true});});
 function show(title,kind){world.atlas?.resources?.cancel();world.cancelCameraMotion();gathering.cancel({clearSelection:true});view=kind;body.replaceChildren();feedback.textContent='';dialog.querySelector('h2').textContent=title;dialog.querySelector('.market-balance').textContent=store.snapshot().coins+' 枚山城铜币';if(!dialog.open){previous=document.activeElement;enabled=cameraInputEnabled(world);controls.enabled=false;dialog.showModal();}dialog.querySelector('header button').focus();}
 function action(fn){const result=fn();gathering.refreshBag();if(view==='directory')showDirectory();else showShop(selected);feedback.textContent=result.message+(result.ok&&!result.saved?' 本次存档失败，刷新可能丢失。':'');}
 function showDirectory(){show('山风集市','directory');body.append(el('p','石街两侧有杂货铺、药房、保管库与驿站。走进商铺，在柜台查看货物和委托。'));for(const r of records){const row=el('section','');row.append(el('h3',r.name),el('p',r.definition.subtitle),button('前往门口',()=>focus(r.market)));body.append(row);}body.append(button('前往旅人客房',()=>handoff(()=>world.atlas.housing.open())));body.append(el('small','铜币和库存只保存在此浏览器。材料可在各地工坊加工，家具可以摆入客房；食物和药水可从 B 行囊使用。'));}
 function showShop(r){selected=r;show(r.name,'shop');const s=store.snapshot();body.append(el('p',r.definition.subtitle));if(!buildings.inside||buildings.selected!==r.id){body.append(button(r.open?'关上店门':'推开店门',()=>{setDoor(r,!r.open);showShop(r);}),button('进入商铺',()=>{if(!r.open)return;close();r.angle=-1.48;r.door.rotation.y=r.angle;buildings.focus(r,true,{lightScale:.42});say('点击柜台查看货物。');},!r.open));return;}
  body.append(button('回到门外',()=>{close();buildings.focus(r,false);}));
  if(r.market==='provisions'||r.market==='apothecary'){for(const g of GOODS.filter(g=>g.shop===r.market)){const row=el('section','');row.append(el('h3',g.name),el('p',`售价 ${g.price} · 回收 ${g.sell} · 行囊 ${s.bag[g.id]||0}`),button('购买一件',()=>action(()=>store.buy(g.id)),s.coins<g.price),button('卖出一件',()=>action(()=>store.sell(g.id)),!s.bag[g.id]));body.append(row);}for(const g of GOODS.filter(g=>!g.shop&&s.bag[g.id]>0)){const row=el('section','');row.append(el('h3',g.name),el('p',`收购 ${g.sell} · 行囊 ${s.bag[g.id]}`),button('出售一件加工品',()=>action(()=>store.sell(g.id))));body.append(row);}body.append(el('small','家具可布置客房；补给可从 B 行囊使用，持续五分钟。'));}
  if(r.market==='vault'){body.append(el('p','寄存与取回不收费。这里保管购买与制作的随身物品，寄存材料不可直接用于制作。'));for(const g of GOODS){const row=el('section','');row.append(el('h3',g.name),el('p',`行囊 ${s.bag[g.id]||0} · 保管库 ${s.vault[g.id]||0}`),button('存入一件',()=>action(()=>store.transfer(g.id,true)),!s.bag[g.id]),button('取回一件',()=>action(()=>store.transfer(g.id,false)),!s.vault[g.id]));body.append(row);}}
  if(r.market==='courier'){if(!s.welcome)body.append(el('h3','旅人见面礼'),el('p','驿站为初来的旅人准备 30 枚铜币。'),button('领取见面礼',()=>action(()=>store.welcome())));body.append(el('h3','五境货单'),el('p','将封好的工坊货单交到五境的工艺台，再回驿站领取 45 枚铜币。货单由驿站提供，不消耗采集物。'));if(s.contract==='available')body.append(button('接取货单委托',()=>action(()=>store.accept())));else{for(const id of DELIVERY_REGIONS){const t=TRADES.find(t=>t.id===id);body.append(el('p',(s.delivered.includes(id)?'✓ 已送达 · ':'○ 待送达 · ')+t.name));}body.append(button(s.contract==='complete'?'委托已完成':'交回签收单 · 领取 45 铜币',()=>action(()=>store.claim()),s.contract==='complete'||s.delivered.length!==5));}body.append(button('打开五境工艺台名录',()=>{handoff(()=>world.atlas.town.showLedger());}));}
 }
 function setDoor(r,open){r.open=!!open;if(reduced.matches){r.angle=r.open?-1.48:0;r.door.rotation.y=r.angle;}say(r.name+(r.open?'的门开了。':'的门关上了。'));}
 function focus(id){const r=records.find(r=>r.market===id);if(!r)return false;close();world.atlas.travel('highland');selected=r;return buildings.focus(r,false);}
 function point(r){return r.root.localToWorld(new T.Vector3(0,1.55,buildings.selected===r.id&&buildings.inside?-.30:2.61));}
 function reachable(r){const p=point(r),v=p.clone().project(camera);return camera.position.distanceTo(p)<8&&Math.abs(v.x)<.95&&Math.abs(v.y)<.9&&v.z>-1&&v.z<1&&!nav.obstructed(camera.position,p.clone().lerp(camera.position,.12),.01);}
 function activate(r){if(isBlocked()||!reachable(r))return;showShop(r);}
 function hit(e){if(isBlocked())return null;const rect=canvas.getBoundingClientRect();ndc.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(ndc,camera);ray.far=8;for(const r of records){if(!reachable(r))continue;const hits=ray.intersectObject(r.root,true).filter(h=>h.object.visible);if(hits.length)return r;}return null;}
 const pd=e=>{if(e.button===0)down={x:e.clientX,y:e.clientY};},pu=e=>{const d=down;down=null;if(!d||e.button!==0||Math.hypot(e.clientX-d.x,e.clientY-d.y)>6)return;const r=hit(e);if(r)queueMicrotask(()=>activate(r));},clear=()=>{down=null;hint.hidden=true;selected=null;close();};
 const key=e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.code==='KeyE'&&!hint.hidden&&selected&&!isBlocked()){e.preventDefault();e.stopImmediatePropagation();activate(selected);}};
 const storage=e=>{if(e.key===MARKET_KEY){store.reload();gathering.refreshBag();if(dialog.open)view==='directory'?showDirectory():showShop(selected);}};
 canvas.addEventListener('pointerdown',pd);canvas.addEventListener('pointerup',pu);const release=()=>down=null;canvas.addEventListener('pointercancel',release);window.addEventListener('blur',release);window.addEventListener('keydown',key,true);window.addEventListener('storage',storage);hint.onclick=()=>selected&&activate(selected);
 function update(){const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;for(const r of records){const target=r.open?-1.48:0;r.angle=T.MathUtils.damp(r.angle,target,7,dt);r.door.rotation.y=r.angle;}if(isBlocked()||document.body.dataset.visitorHidden==='true'){hint.hidden=true;return;}selected=records.find(reachable)||null;if(!selected){hint.hidden=true;return;}const p=point(selected).project(camera);hint.hidden=false;hint.style.left=T.MathUtils.clamp((p.x*.5+.5)*innerWidth,115,innerWidth-115)+'px';hint.style.top=T.MathUtils.clamp((-p.y*.5+.5)*innerHeight-75,110,innerHeight-250)+'px';hint.textContent=selected.name+(buildings.inside?' · 柜台 · E':' · 店门 · E');}
 return{records,store,focus,showDirectory,update,clear,setDoor,stats:()=>({state:store.snapshot(),shops:records.map(r=>({id:r.market,reachable:reachable(r),open:r.open,angle:r.angle,position:r.root.getWorldPosition(new T.Vector3()).toArray()}))}),dispose(){clear();removeDynamic.forEach(fn=>fn());architecture.dispose();dialog.remove();hint.remove();canvas.removeEventListener('pointerdown',pd);canvas.removeEventListener('pointerup',pu);canvas.removeEventListener('pointercancel',release);window.removeEventListener('blur',release);window.removeEventListener('keydown',key,true);window.removeEventListener('storage',storage);}};
}
