import {cameraInputEnabled,restoreCameraInput} from './camera-input.js';
import * as T from 'three';
import {RESOURCE_TYPES,RESOURCE_SITES,RESOURCE_SKILLS,resourceDuration,resourceLevel} from './resource-content.js';
import {GOODS,MARKET_KEY} from './market-content.js';
import {createResourceMaterials,makeResource,makeCharcoalKiln,makeHandMill} from './resource-props.js';
import './resources.css';
export function createResources(world,{settlements,nav,market,gathering,town,isBlocked,say}){
 const {camera,controls}=world,canvas=world.renderer.domElement,materials=createResourceMaterials(settlements.materials),records=[],extras=[],reservations=[],seen=new Set(),ray=new T.Raycaster(),pointer=new T.Vector2(),groundRay=new T.Raycaster(),reduced=matchMedia('(prefers-reduced-motion: reduce)');let task=null,down=null,hovered=null,viewRecord=null,lastAnchor=new T.Vector3(),previous=null,enabled=true,last=0,disposed=false;
 const dialog=document.createElement('dialog');dialog.className='resource-directory';dialog.setAttribute('aria-labelledby','resource-title');dialog.innerHTML='<header><div><small>五境 · 原料与产地</small><h2 id="resource-title">沿着手艺，寻找原料</h2></div><button aria-label="关闭原料产地">×</button></header><p>矿石、草药、陶土与木材都能收入行囊，在原有工坊继续加工。</p><div class="resource-skills"></div><div class="resource-list"></div><p class="resource-feedback" role="status"></p>';
 const hint=document.createElement('button');hint.className='resource-hint';hint.hidden=true;
 const activity=document.createElement('section');activity.className='resource-activity';activity.hidden=true;activity.innerHTML='<strong></strong><p role="status"></p><progress max="1"></progress><button>收起工具 · Esc</button>';
 document.body.append(dialog,hint,activity);const button=(label,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;return b;};
 function close(){if(dialog.open)dialog.close();}
 dialog.querySelector('header button').onclick=close;dialog.addEventListener('close',()=>{if(!document.querySelector('dialog[open]')&&!task)restoreCameraInput(world,enabled);(previous?.isConnected?previous:canvas).focus({preventScroll:true});});
 function showDirectory(){if(isBlocked())return false;gathering.cancel({clearSelection:true});world.cancelCameraMotion();renderDirectory();previous=document.activeElement;enabled=cameraInputEnabled(world);controls.enabled=false;dialog.showModal();dialog.querySelector('header button').focus();return true;}
 function renderDirectory(){const state=market.store.snapshot(),skills=dialog.querySelector('.resource-skills');skills.textContent=RESOURCE_SKILLS.map(id=>id+' '+resourceLevel(state.harvest.xp[id])+'/5').join(' · ');const list=dialog.querySelector('.resource-list');list.replaceChildren();for(const site of RESOURCE_SITES){const type=RESOURCE_TYPES[site.kind],r=records.find(r=>r.id===site.id),section=document.createElement('article');section.dataset.resource=site.id;const h=document.createElement('h3');h.textContent=type.name;const p=document.createElement('p');p.textContent=site.place+' · '+(r?.region.name||{aether:'浮空群岛',highland:'牛角山城',forest:'紫境森林',watercourt:'精灵水庭',valley:'北境河谷'}[site.region])+' · '+GOODS.find(g=>g.id===type.item).name+' × '+type.yield;const status=document.createElement('small');status.dataset.resourceStatus=site.id;section.append(h,p,status);const b=button(r?'前往这处产地':'展开城镇并前往',async()=>{b.disabled=true;b.textContent='正在展开目的地…';await world.atlas.readyFor(site.region);if(!dialog.open||disposed)return;if(!records.some(r=>r.id===site.id)){b.disabled=false;b.textContent='加载未完成，点击重试';return;}dialog.addEventListener('close',()=>focus(site.id),{once:true});close();});section.append(b);list.append(section);}refreshLabels();}
 function refreshLabels(){for(const n of dialog.querySelectorAll('[data-resource-status]')){const status=market.store.resourceStatus(n.dataset.resourceStatus);n.textContent=status.ok?'可以采收':status.remaining?'恢复中 · '+Math.ceil(status.remaining/1000)+' 秒':status.message;}}
 function worldPoint(r){return r.root.localToWorld(r.prop.anchor.clone());}
 function chooseSite(site,region,source){const naturals=[];source.updateWorldMatrix(true,true);source.traverse(o=>{if(!o.isMesh||o.userData.crafted||o.userData.noCollision)return;if(site.surface?o.name===site.surface:/^Forest_floor|^Violet.*ground|^Moss_islands_and_forest_banks|^Alpine_valley_terrain|^Horncrest_ground|_terrace$/i.test(o.name))naturals.push(o);});
  let center;if(site.xz)center=new T.Vector3(site.xz[0],0,site.xz[1]);else if(naturals.length){center=new T.Box3().setFromObject(naturals[0]).getCenter(new T.Vector3());center.x+=site.offset?.[0]||0;center.z+=site.offset?.[1]||0;}else return null;
  const minY={aether:-5,highland:7,forest:.55,watercourt:8.35,valley:1.65}[region.id],normal=new T.Vector3(),matrix=new T.Matrix4(),instance=new T.Matrix4();
  for(let ring=0;ring<=10;ring+=1.25)for(let k=0;k<(ring?16:1);k++){const angle=k*Math.PI/8,p=center.clone().add(new T.Vector3(Math.cos(angle)*ring,0,Math.sin(angle)*ring));let parent=source;
   if(site.quay){const y=nav.height(p.x,p.z,11,9);if(y===null)continue;p.y=y;}
   else{groundRay.set(new T.Vector3(p.x,150,p.z),new T.Vector3(0,-1,0));const hits=groundRay.intersectObjects(naturals,false);const hit=hits.find(hit=>{matrix.copy(hit.object.matrixWorld);if(hit.object.isInstancedMesh){hit.object.getMatrixAt(hit.instanceId,instance);matrix.multiply(instance);}return normal.copy(hit.face.normal).applyNormalMatrix(new T.Matrix3().getNormalMatrix(matrix)).y>.75;});if(!hit)continue;p.copy(hit.point);for(let o=hit.object;o;o=o.parent)if(o.userData.floating){parent=o;break;}}
   if(p.y<minY||!nav.clearBody(p)||records.some(r=>r.root.getWorldPosition(new T.Vector3()).distanceTo(p)<2.5))continue;
   if(Math.hypot(p.x-region.spawn[0],p.z-region.spawn[2])<3||region.id==='aether'&&Math.hypot(p.x+25.6,p.z+22.8)<5)continue;
   if(settlements.records.some(r=>r.region===region.id&&r.inspect!==false&&r.type!=='ruin'&&r.type!=='totem'&&(()=>{const c=r.root.getWorldPosition(new T.Vector3()),scale=r.root.getWorldScale(new T.Vector3()).x;return Math.abs(c.y-p.y)<8&&Math.hypot(c.x-p.x,c.z-p.z)<(r.radius||2)*scale+1;})()))continue;
   let safe=true;for(const [x,z]of [[.65,0],[-.65,0],[0,.65],[0,-.65]]){const h=nav.height(p.x+x,p.z+z,p.y+.45,p.y-.45);if(h===null||Math.abs(h-p.y)>.28||!nav.clearBody(new T.Vector3(p.x+x,h,p.z+z))){safe=false;break;}}if(safe)return{position:p,parent};
  }return null;
 }
 function add(region,source){if(seen.has(region.id))return;seen.add(region.id);for(const site of RESOURCE_SITES.filter(s=>s.region===region.id)){const spot=chooseSite(site,region,source);if(!spot)continue;const prop=makeResource(materials.mats,site.kind,RESOURCE_SITES.indexOf(site)+1,{winter:region.id==='valley',treeParts:site.kind==='wood'?['Alpine_fir_needles_0','Alpine_fir_trunks_0','Pine_dense_inner_crown_0'].map(name=>source.getObjectByName(name)).filter(Boolean):[]}),root=prop.root;spot.parent.add(root);root.position.copy(spot.parent.worldToLocal(spot.position.clone()));root.scale.setScalar(1/spot.parent.getWorldScale(new T.Vector3()).x);root.updateWorldMatrix(true,true);const r={id:site.id,site,region,prop,root,parent:spot.parent,position:spot.position.toArray(),available:true,source,foliage:[]};source.traverse(o=>{if(o.isMesh&&/trunk|bark|stem|canopy|needles|crown|HC pine/i.test(o.name+' '+o.material?.name)&&!o.userData.crafted)r.foliage.push(o);});records.push(r);nav.add(prop.fixed);if(prop.proxy)r.removeCollider=nav.addDynamic(prop.proxy);reservations.push(gathering.flora.reserveArea(spot.position,site.kind==='ore'||site.kind==='sand'?1.85:1.35));}
  if(region.id==='valley'){const house=settlements.records.find(r=>r.region==='valley'&&r.type==='house');if(house){const kiln=makeCharcoalKiln(materials.mats),p=house.root.localToWorld(new T.Vector3(5.4,0,1)),y=nav.height(p.x,p.z,p.y+1,p.y-5);if(y!==null){p.y=y;source.add(kiln.root);kiln.root.position.copy(source.worldToLocal(p));kiln.root.scale.setScalar(1/source.getWorldScale(new T.Vector3()).x);nav.add(kiln.root);extras.push(kiln.root);town.registerWorkshop({id:'charcoal-kiln',profession:'valley',recipeIds:['charcoal'],name:'雪线炭窑',outdoor:true,building:house,prop:kiln});}}}
  if(region.id==='highland'){const room=settlements.records.find(r=>r.name==='山城木屋 02');if(room){const mill=makeHandMill(materials.mats);room.root.add(mill.root);mill.root.position.set(3.65,.10,-1.75);const p=mill.root.getWorldPosition(new T.Vector3()),y=nav.height(p.x,p.z,p.y+.15,p.y-.5);if(y!==null){p.y=y+.002;mill.root.position.copy(room.root.worldToLocal(p));}nav.add(mill.root);extras.push(mill.root);town.registerWorkshop({id:'mill',profession:'kitchen',recipeIds:['flour'],name:'厨房石磨',building:room,prop:mill});}}
  if(dialog.open)renderDirectory();
 }
 function focus(id){if(isBlocked())return false;const r=records.find(r=>r.id===id);if(!r)return false;world.atlas.travel(r.region.id);world.cancelCameraMotion();nav.sync();const target=worldPoint(r),offset=new T.Vector3();let chosen=null,best=Infinity;for(let i=0;i<16;i++){const angle=i*Math.PI/8;offset.set(Math.cos(angle)*4.1,2.1,Math.sin(angle)*4.1);const eye=target.clone().add(offset),y=nav.height(eye.x,eye.z,eye.y+2);if(y!==null)eye.y=Math.max(eye.y,y+1.3);if(eye.y-target.y>5||nav.obstructed(eye,eye,.28)||nav.obstructed(eye,target.clone().lerp(eye,.26),.01))continue;const side=new T.Vector3().crossVectors(target.clone().sub(eye),camera.up).normalize(),occluders=r.foliage.filter(o=>o.visible);let score=0;for(const [x,y]of [[0,0],[-.65,0],[.65,0],[0,.7]]){const end=target.clone().addScaledVector(side,x);end.y+=y;ray.set(eye,end.clone().sub(eye).normalize());ray.far=eye.distanceTo(end)-.45;score+=ray.intersectObjects(occluders,false).slice(0,20).reduce((n,h)=>n+1/(.2+h.distance),0);}if(score<best){best=score;chosen=eye;}if(score===0)break;}if(!chosen){say('这处产地暂时没有清晰的观察角度，请从附近环顾。');return false;}camera.position.copy(chosen);controls.target.copy(target);camera.lookAt(target);controls.update();viewRecord=r;lastAnchor.copy(r.root.getWorldPosition(new T.Vector3()));hovered=r;document.body.dataset.atlasInspecting='true';say(RESOURCE_TYPES[r.site.kind].hint);return true;}
 function visible(r){for(let o=r.root;o;o=o.parent)if(!o.visible)return false;return true;}
 function reachable(r){if(!visible(r))return false;const p=worldPoint(r),v=p.clone().project(camera);if(camera.position.distanceTo(p)>11||v.z< -1||v.z>1||Math.abs(v.x)>.92||Math.abs(v.y)>.88)return false;ray.set(camera.position,p.clone().sub(camera.position).normalize());ray.far=12;const hit=ray.intersectObject(r.root,true).find(h=>h.object.visible);const end=(hit?.point||p).clone().lerp(camera.position,.015);return !nav.obstructed(camera.position,end,.005);}
 function start(r){if(task||isBlocked()||!r||!reachable(r))return false;market.store.reload();const check=market.store.resourceStatus(r.id);if(!check.ok){say(check.remaining?'这处原料还需 '+Math.ceil(check.remaining/1000)+' 秒恢复。':check.message);return false;}gathering.cancel({clearSelection:true});world.cancelCameraMotion();const type=RESOURCE_TYPES[r.site.kind],state=market.store.snapshot();task={r,start:performance.now(),duration:resourceDuration(r.site.kind,state.harvest.xp[type.tool],market.store.effect('tonic')>0),camera:camera.position.clone(),target:controls.target.clone(),enabled:cameraInputEnabled(world),committing:false};document.body.dataset.resourceBusy='true';controls.enabled=false;hint.hidden=true;activity.hidden=false;activity.querySelector('strong').textContent=type.verb;activity.querySelector('p').textContent='原料在作业完成后收入行囊。';activity.querySelector('progress').value=0;activity.querySelector('button').focus();return true;}
 function cancel(message){const old=task;if(!old)return;task=null;old.r.prop.update(null,reduced.matches);delete document.body.dataset.resourceBusy;activity.hidden=true;if(!document.querySelector('dialog[open]'))restoreCameraInput(world,old.enabled);if(message)say(message);canvas.focus({preventScroll:true});}
 async function finish(current){if(task!==current||current.committing)return;current.committing=true;const transact=()=>{if(task!==current||disposed)return null;market.store.reload();return market.store.harvest(current.r.id);};let result;try{result=navigator.locks?await navigator.locks.request(MARKET_KEY,transact):transact();}catch{result={ok:false,message:'这次作业未能保存，请重试。'};}if(task!==current)return;cancel();if(result){gathering.refreshBag();say(result.message);}sync();}
 function sync(){for(const r of records){const check=market.store.resourceStatus(r.id);r.available=!check.remaining;r.prop.setAvailable(r.available);if(r.prop.proxy){if(!r.available&&r.removeCollider){r.removeCollider();r.removeCollider=null;}else if(r.available&&!r.removeCollider)r.removeCollider=nav.addDynamic(r.prop.proxy);}}}
 function clear(){cancel();viewRecord=null;hovered=null;down=null;hint.hidden=true;close();}
 function hit(e){if(isBlocked()||document.body.dataset.visitorHidden==='true')return null;const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);ray.far=12;const hits=ray.intersectObjects(records.filter(visible).map(r=>r.root),true).filter(h=>h.object.visible);if(!hits.length)return null;const first=hits[0];if(nav.obstructed(camera.position,first.point.clone().lerp(camera.position,.015),.005))return null;let o=first.object;while(o){const r=records.find(r=>r.root===o);if(r)return r;o=o.parent;}return null;}
 const pd=e=>{if(e.button===0)down=[e.clientX,e.clientY];},pu=e=>{const startPoint=down;down=null;if(!startPoint||e.button!==0||Math.hypot(e.clientX-startPoint[0],e.clientY-startPoint[1])>6)return;const r=hit(e);if(r)queueMicrotask(()=>start(r));};
 const blur=()=>{down=null;cancel('作业已收起，未完成的原料没有领取。');},key=e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.code==='Escape'&&task){e.preventDefault();e.stopImmediatePropagation();cancel('已收起工具。');}else if(e.code==='KeyE'&&!hint.hidden&&hovered&&!isBlocked()){e.preventDefault();e.stopImmediatePropagation();start(hovered);}};hint.onclick=()=>start(hovered);activity.querySelector('button').onclick=()=>cancel('已收起工具。');const visibility=()=>{if(document.hidden)blur();},storage=e=>{if(e.key===MARKET_KEY){market.store.reload();sync();gathering.refreshBag();if(dialog.open)renderDirectory();}};
 canvas.addEventListener('pointerdown',pd);canvas.addEventListener('pointerup',pu);canvas.addEventListener('pointercancel',blur);window.addEventListener('blur',blur);window.addEventListener('keydown',key,true);document.addEventListener('visibilitychange',visibility);window.addEventListener('storage',storage);
 function update(){const now=performance.now();if(viewRecord){const anchor=viewRecord.root.getWorldPosition(new T.Vector3()),delta=anchor.clone().sub(lastAnchor);camera.position.add(delta);controls.target.add(delta);if(task){task.camera.add(delta);task.target.add(delta);}lastAnchor.copy(anchor);}if(task){const active=task;if(document.hidden||document.querySelector('dialog[open]')||document.body.dataset.townBusy==='true'||document.body.dataset.homeEditing==='true'||world.atlas.transition.busy||camera.position.distanceTo(active.camera)>.45||controls.target.distanceTo(active.target)>.45){cancel('视角已离开，作业已收起。');return;}const progress=Math.min(1,(now-active.start)/active.duration);activity.querySelector('progress').value=progress;active.r.prop.update(progress,reduced.matches);if(progress>=1)finish(active);return;}if(now-last<200)return;last=now;sync();for(const r of records)r.prop.update(null,reduced.matches);if(dialog.open)refreshLabels();if(isBlocked()||document.body.dataset.visitorHidden==='true'){hint.hidden=true;return;}hovered=records.find(reachable)||null;hint.hidden=!hovered;if(hovered){const point=worldPoint(hovered).project(camera),type=RESOURCE_TYPES[hovered.site.kind],check=market.store.resourceStatus(hovered.id);hint.style.left=T.MathUtils.clamp((point.x*.5+.5)*innerWidth,115,innerWidth-115)+'px';hint.style.top=T.MathUtils.clamp((-.5*point.y+.5)*innerHeight-50,115,innerHeight-250)+'px';hint.textContent=check.remaining?type.name+' · 恢复 '+Math.ceil(check.remaining/1000)+' 秒':type.verb+' · E';hint.disabled=!!check.remaining;hint.dataset.resource=hovered.id;}}
 return{add,records,showDirectory,focus,start,cancel,clear,update,stats:()=>({sites:records.map(r=>({id:r.id,region:r.region.id,kind:r.site.kind,position:r.root.getWorldPosition(new T.Vector3()).toArray(),parent:r.parent.name,available:r.available,reachable:reachable(r)})),task:task?{id:task.r.id,duration:task.duration,committing:task.committing}:null,state:market.store.snapshot().harvest,extras:extras.map(r=>({name:r.children[0]?.name,position:r.getWorldPosition(new T.Vector3()).toArray()}))}),dispose(){disposed=true;clear();reservations.forEach(fn=>fn());records.forEach(r=>{r.removeCollider?.();r.prop.dispose();});materials.dispose();dialog.remove();hint.remove();activity.remove();canvas.removeEventListener('pointerdown',pd);canvas.removeEventListener('pointerup',pu);canvas.removeEventListener('pointercancel',blur);window.removeEventListener('blur',blur);window.removeEventListener('keydown',key,true);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('storage',storage);}};
}
