import * as T from 'three';
import {attachBranchSnow} from '../valley/branch-snow.js';
import {Craft} from './architecture-kit.js';
import {winterVegetation,cloneVegetationMaterial} from '../valley/winter-vegetation.js';
export function createResourceMaterials(shared){const loader=new T.TextureLoader(),maps=['rock-color','rock-normal','rock-rough'].map(name=>loader.load(import.meta.env.BASE_URL+'aether/textures/'+name+'.jpg'));maps[0].colorSpace=T.SRGBColorSpace;maps.forEach(t=>{t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=4;});const own={rock:new T.MeshStandardMaterial({color:'#a0a4a0',map:maps[0],normalMap:maps[1],roughnessMap:maps[2],normalScale:new T.Vector2(.3,.3),roughness:.9}),copper:new T.MeshStandardMaterial({color:'#ac7750',metalness:.7,roughness:.52}),soil:new T.MeshStandardMaterial({color:'#665546',roughness:1}),sand:new T.MeshStandardMaterial({color:'#bcad86',map:maps[0],roughness:1}),clay:new T.MeshStandardMaterial({color:'#9b7763',map:maps[0],roughness:.95}),leaf:new T.MeshStandardMaterial({color:'#597763',roughness:.9,side:T.DoubleSide}),herb:new T.MeshStandardMaterial({color:'#9ca879',roughness:.95,side:T.DoubleSide}),grain:new T.MeshStandardMaterial({color:'#c3a15f',roughness:.94}),water:new T.MeshPhysicalMaterial({color:'#88b7be',roughness:.18,transmission:.65,thickness:.05,ior:1.33})};Object.entries(own).forEach(([key,m])=>m.name='Field materials · '+key);return{mats:{...shared,...own},dispose(){Object.values(own).forEach(m=>m.dispose());maps.forEach(t=>t.dispose());}};}
function rock(c,p,size,seed=0,kind='rock'){const g=new T.DodecahedronGeometry(1,1),a=g.attributes.position;for(let i=0;i<a.count;i++){const x=a.getX(i),y=a.getY(i),z=a.getZ(i),n=.93+.08*Math.sin(x*8+y*7+z*3+seed);a.setXYZ(i,x*size[0]*n,y*size[1]*n,z*size[2]*n);}g.computeVertexNormals();c.add(g,kind,p);}
function leaf(c,p,size,rot,kind='leaf'){let g;if(kind!=='grain'&&size[2]<.04){const pos=[],uv=[],idx=[];for(let i=0;i<=8;i++){const t=i/8,w=Math.pow(Math.sin(t*Math.PI),.75)*size[0];for(const side of [-1,1]){pos.push(side*w,(t*2-1)*size[1],Math.sin(t*Math.PI)*size[2]);uv.push((side+1)/2,t);}if(i<8){const k=i*2;idx.push(k,k+1,k+2,k+1,k+3,k+2);}}g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();}else{g=new T.SphereGeometry(1,8,5);g.scale(...size);}c.add(g,kind,p,rot);}

function pick(c){c.tube([0,-.6,0],[0,.6,0],.045);c.line([[-.55,.5,0],[-.3,.64,0],[0,.65,0],[.36,.56,0],[.54,.41,0]],.055,'iron');for(const s of [-1,1])c.tube([s*.52,.43,0],[s*.72,.23,0],.045,'iron',.008);c.box([0,.61,0],[.17,.22,.15],'iron');}
function shovel(c){c.tube([0,-.4,0],[0,.75,0],.033);c.add(new T.TorusGeometry(.12,.025,6,16),'wood',[0,.82,0]);const g=new T.SphereGeometry(1,12,8);g.scale(.18,.29,.03);c.add(g,'iron',[0,-.6,0]);}
export function makeResource(mats,kind,seed,{treeParts=[],winter=false}={}){const root=new T.Group();root.name='Resource · '+kind+' · '+seed;const own=[];if(winter){mats={...mats};for(const key of ['leaf','herb']){mats[key]=winterVegetation(mats[key].clone(),{ground:true});own.push(mats[key]);}}const base=new Craft(mats,'资源底座 · '+kind),body=new Craft(mats,'可采原料 · '+kind),tool=new Craft(mats,'作业工具 · '+kind);let anchor=new T.Vector3(0,.65,0),toolType='strike';
 if(kind==='ore'){rock(base,[0,.42,0],[.93,.60,.75],seed);for(let i=0;i<13;i++){const a=i*2.4,x=Math.cos(a)*.64,z=Math.sin(a)*.5,y=.51+.30*Math.sin(i*1.4);rock(body,[x,y,z],[.15,.13,.11],seed+i,'copper');}for(let i=0;i<5;i++){const z=-.45+i*.19;body.line([[-.62,.58,z],[-.32,.83,z+.04],[.03,.96,z],[.34,.80,z-.07],[.58,.64,z]],.024,'copper');}pick(tool);}
 if(kind==='sand'||kind==='clay'){rock(base,[0,.035,0],[1.1,.13,.85],seed,kind==='sand'?'soil':'rock');for(let i=0;i<19;i++){const a=i*2.4,r=Math.sqrt((i+.5)/19)*.86;rock(body,[Math.cos(a)*r,.11+Math.sin(i)*.04,Math.sin(a)*r*.72],[.29,.13,.23],seed+i,kind);}for(let i=0;i<9;i++){const a=i*2.4;rock(base,[Math.cos(a)*1.05,.07,Math.sin(a)*.83],[.12,.1,.14],i);}shovel(tool);anchor.y=.25;}
 if(kind==='wood'){base.cylinder([0,.16,0],.24,.32,'wood',.21,14);base.cylinder([0,.326,0],.196,.016,'endgrain',.196,20);if(!treeParts.length){body.cylinder([0,1.62,0],.20,2.6,'wood',.065,14);for(let level=0;level<5;level++){const y=.9+level*.48,r=1.05-level*.16;for(let j=0;j<7;j++){const a=j*Math.PI*2/7+level*.53,xx=Math.cos(a)*r,zz=Math.sin(a)*r;body.tube([0,y+.22,0],[xx,y,zz],.035,'wood',.006);for(let k=1;k<=4;k++)leaf(body,[xx*k/4,y+.1,zz*k/4],[.20,.13,.42],[.15,-a+Math.PI/2,.2],'leaf');}}leaf(body,[0,3.26,0],[.19,.46,.19],[0,0,0]);}tool.tube([0,-.6,0],[0,.55,0],.045);tool.box([.11,.49,0],[.42,.27,.10],'iron',[0,0,.17]);toolType='fell';anchor.y=1.1;}
 if(kind==='herb'||kind==='pine'||kind==='grain'){rock(base,[0,-.03,0],[.83,.09,.68],seed,'soil');for(let i=0;i<(kind==='grain'?35:13);i++){const a=i*2.4,r=.68*Math.sqrt((i+.5)/(kind==='grain'?35:13)),x=Math.cos(a)*r,z=Math.sin(a)*r*.8,h=kind==='grain'?.80+.25*Math.sin(i):.30+.2*Math.sin(i*2);body.tube([x,.02,z],[x+.07,h,z],.01,kind==='grain'?'grain':'leaf',.005,5);for(let j=0;j<4;j++)for(const s of [-1,1]){if(kind==='grain')leaf(body,[x+.07+s*.043,h+j*.047,z],[.036,.09,.027],[0,0,-s*.5],'grain');else leaf(body,[x+s*.08,.08+j*.075,z],[.07,.13,.023],[0,j*.8,s*.8],kind==='herb'?'herb':'leaf');}if(kind==='herb')body.sphere([x+.07,h+.08,z],[.047,.046,.047],'amethyst');base.tube([x,0,z],[x,.08,z],.011,kind==='grain'?'grain':'leaf',.009,5);}tool.tube([0,-.4,0],[0,.22,0],.038);tool.line([[0,.2,0],[.24,.32,0],[.41,.18,0],[.38,-.05,0],[.2,-.22,0]],.032,'iron');anchor.y=kind==='grain'?.8:.3;toolType='cut';}
 if(kind==='water'){for(const x of [-.45,.45])base.box([x,.05,0],[.26,.1,1.3]);base.cylinder([0,.2,0],.3,.3,'iron',.24,16);base.cylinder([0,.81,0],.115,1.05,'copper',.12,16);base.cylinder([0,1.42,0],.20,.20,'iron',.18,16);base.line([[0,1.15,0],[.35,1.15,0],[.44,1.06,0]],.065,'copper');for(let j=0;j<18;j++){const a=j*Math.PI/9,x=.5+Math.cos(a)*.26,z=Math.sin(a)*.26;base.tube([x,.12,z],[x,.6,z],.042,'wood');}for(const y of [.2,.53,.61])base.ring([.5,y,0],.28,.022,'iron');base.cylinder([.5,.125,0],.25,.05,'wood',.25,24);body.cylinder([.5,.595,0],.23,.016,'water',.23,24);tool.box([0,0,0],[.09,.12,.12],'iron');tool.tube([0,0,0],[.6,-.1,0],.035,'iron');tool.cylinder([.61,-.1,0],.055,.24,'wood',.055,12);anchor.set(0,1,0);toolType='pump';}
 const fixed=base.finish(root),harvest=body.finish(root),implement=tool.finish(root,kind==='water'?[0,1.43,0]:[1.05,kind==='sand'||kind==='clay'?.9:kind==='ore'||kind==='wood'?.62:.42,.25],-.3);harvest.traverse(o=>{if(o.isMesh)o.userData.noCollision=true;});implement.traverse(o=>{if(o.isMesh)o.userData.noCollision=true;});if(['herb','pine','grain'].includes(kind))fixed.traverse(o=>o.userData.noCollision=true);
 for(const source of treeParts){const material=cloneVegetationMaterial(source.material);own.push(material);const tree=new T.Mesh(source.geometry.clone(),material);tree.scale.setScalar(.46);tree.userData.noCollision=true;tree.castShadow=tree.receiveShadow=true;tree.name='作业松 · '+source.name;tree.visible=source.visible;for(const child of source.children){if(!child.material?.userData.winterBranchSnow)continue;const snowMat=cloneVegetationMaterial(child.material);own.push(snowMat);attachBranchSnow(tree,child.geometry.clone(),snowMat);}harvest.add(tree);}let proxy=null;if(kind==='wood'){proxy=new T.Mesh(new T.CylinderGeometry(.065,.20,2.6,10));proxy.position.set(0,1.62,0);proxy.visible=false;proxy.userData.noCollision=true;harvest.add(proxy);}
 const geo=new T.BufferGeometry(),coords=new Float32Array(30*3);geo.setAttribute('position',new T.BufferAttribute(coords,3));const mat=new T.PointsMaterial({color:kind==='water'?'#b0e9e8':kind==='ore'?'#cb9b60':kind==='wood'?'#bc996f':'#b2b884',size:.035,transparent:true,opacity:0,depthWrite:false});const dust=new T.Points(geo,mat);dust.userData.noCollision=true;root.add(dust);let available=true;
 function update(progress,reduced=false){const active=progress!==null,phase=(progress||0)*4*Math.PI*2;implement.rotation.z=active&&!reduced?(kind==='water'?Math.sin(phase)*.30:Math.sin(phase)*.65):-.2;harvest.rotation.z=active&&toolType==='fell'&&!reduced?Math.max(0,((progress||0)-.76)/.24)*1.42:0;harvest.position.y=0;harvest.visible=available;mat.opacity=active&&!reduced?.72:0;for(let i=0;i<30;i++){const t=((progress||0)*4+i/30)%1,a=i*2.4;coords[i*3]=kind==='water'?.46+Math.sin(a)*.018:Math.cos(a)*t*.6;coords[i*3+1]=kind==='water'?1.06-t*.45:anchor.y+Math.sin(t*Math.PI)*.45-t*.2;coords[i*3+2]=kind==='water'?Math.cos(a)*.018:Math.sin(a)*t*.6;}geo.attributes.position.needsUpdate=true;}
 return{root,fixed,harvest,implement,anchor,kind,proxy,setAvailable(value){available=value;harvest.visible=value;},update,dispose(){root.traverse(o=>o.geometry?.dispose());mat.dispose();own.forEach(m=>m.dispose());proxy?.material.dispose();root.removeFromParent();}};
}
// The opening is cut from the lower shell; the upper dome and chimney remain hollow.
export function makeCharcoalKiln(mats){
 const root=new T.Group();root.name='雪线炭窑';const c=new Craft(mats,'雪线炭窑'),edge=.52;
 c.cylinder([0,.12,0],1.05,.24,'stone',1.05,32);
 const lower=[[.95,.22],[.93,.7],[.82,.91],[.90,.91],[1.03,.7],[1.05,.22],[.95,.22]].reverse().map(p=>new T.Vector2(...p));
 c.add(new T.LatheGeometry(lower,40,edge,Math.PI*2-edge*2),'clay');
 // Solid radial jamb end caps close both exposed edges of the thick shell.
 for(const a of [-edge,edge]){const pts=lower.slice(0,-1).map(p=>[Math.sin(a)*p.x,p.y,Math.cos(a)*p.x]),pos=[],uv=[];for(let i=1;i<pts.length-1;i++)for(const j of [0,i,i+1]){pos.push(...pts[j]);uv.push(pts[j][0],pts[j][1]);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));const capNormal=new T.Vector3().subVectors(new T.Vector3(...pts[1]),new T.Vector3(...pts[0])).cross(new T.Vector3().subVectors(new T.Vector3(...pts[2]),new T.Vector3(...pts[0]))),outward=new T.Vector3(-Math.sign(a)*Math.cos(a),0,Math.sign(a)*Math.sin(a));if(capNormal.dot(outward)<0){const v=g.attributes.position;for(let i=0;i<v.count;i+=3){const b=new T.Vector3().fromBufferAttribute(v,i+1),d=new T.Vector3().fromBufferAttribute(v,i+2);v.setXYZ(i+1,...d.toArray());v.setXYZ(i+2,...b.toArray());}}g.computeVertexNormals();c.add(g,'clay');}
 const upper=[[.82,.91],[.70,1.26],[.3,1.55],[.24,1.7],[.36,1.73],[.39,1.5],[.75,1.16],[.90,.91],[.82,.91]].reverse().map(p=>new T.Vector2(...p));c.add(new T.LatheGeometry(upper,40),'clay');
 for(const side of [-1,1])for(let i=0;i<4;i++)c.box([side*.46,.30+i*.16,.94],[.16,.15,.19],'stone');c.box([0,.96,.92],[1.1,.15,.23],'stone');c.box([0,.27,1],[.72,.07,.25],'iron');for(let i=0;i<5;i++)c.tube([-.32+i*.15,.32,.12],[-.32+i*.15,.35,.94],.055,'wood');c.finish(root);
 const emberMat=new T.MeshStandardMaterial({color:'#4a2414',emissive:'#e66419',emissiveIntensity:0,roughness:.9}),ember=new T.Mesh(new T.SphereGeometry(1,12,6),emberMat);ember.scale.set(.38,.035,.38);ember.position.set(0,.30,.35);ember.userData.noCollision=true;root.add(ember);
 const light=new T.PointLight('#f3a65a',0,3,2);light.position.set(0,.5,.8);root.add(light);let active=false,pulsed=0;
 return{root,anchor:new T.Vector3(0,.58,1.07),setActive(v){active=v;},pulse(){pulsed=performance.now();},update(now,reduced){const t=active?1:Math.max(0,1-(now-pulsed)/1600),f=reduced?1:.9+.1*Math.sin(now*.013);emberMat.emissiveIntensity=t*f*1.8;light.intensity=t*f*1.2;},dispose(){root.traverse(o=>o.geometry?.dispose());emberMat.dispose();root.removeFromParent();}};
}
export function makeHandMill(mats){
 const root=new T.Group();root.name='厨房石磨';const c=new Craft(mats,'厨房石磨');c.box([0,.38,0],[.9,.76,.78]);c.cylinder([0,.81,0],.48,.12,'stone',.48,32);c.box([0,.7,.52],[.56,.14,.34],'wood');c.sphere([0,.81,.5],[.2,.06,.12],'paper');c.finish(root);
 const wheel=new Craft(mats,'转动磨盘');wheel.cylinder([0,.95,0],.45,.15,'pale',.4,32);wheel.cylinder([.29,1.15,0],.035,.28,'wood',.035,10);wheel.cylinder([0,1.035,0],.08,.03,'darkstone',.08,16);for(let i=0;i<8;i++){const a=i*Math.PI/4;wheel.tube([Math.cos(a)*.17,1.028,Math.sin(a)*.17],[Math.cos(a+.23)*.37,1.028,Math.sin(a+.23)*.37],.007,'darkstone');}const rotor=wheel.finish(root);rotor.traverse(o=>{o.userData.noCollision=true;});
 const g=new T.BufferGeometry(),coords=new Float32Array(18*3);g.setAttribute('position',new T.BufferAttribute(coords,3));const m=new T.PointsMaterial({color:'#dcc7a5',size:.02,transparent:true,opacity:0,depthWrite:false}),dust=new T.Points(g,m);dust.userData.noCollision=true;root.add(dust);let active=false,last=0;
 return{root,rotor,anchor:new T.Vector3(0,1.10,.15),setActive(v){active=v;last=performance.now();},pulse(){},update(now,reduced){if(active&&!reduced)rotor.rotation.y+=(now-last)*.003;last=now;m.opacity=active&&!reduced?.6:0;for(let i=0;i<18;i++){const t=(now*.001+i/18)%1;coords[i*3]=Math.sin(i*2.4)*.09;coords[i*3+1]=.90-t*.09;coords[i*3+2]=.47+Math.cos(i*2.4)*.04;}g.attributes.position.needsUpdate=true;},dispose(){root.traverse(o=>o.geometry?.dispose());m.dispose();root.removeFromParent();}};
}
