import {paintFolioBase} from './manuscript-craft.js';
import {cameraInputEnabled,restoreCameraInput} from './camera-input.js';
import * as T from 'three';
import {createStarHallArchitecture} from './star-hall-architecture.js';
import {STAR_CHARTS,STAR_TOLERANCE,STAR_HOLD_SECONDS,angularError} from './star-hall-content.js';
import {MARKET_KEY} from './market-content.js';
import './star-hall.css';
export function createStarHall(world,{source,settlements,nav,buildings,market,gathering,environment,isBlocked,say}){
 const art=createStarHallArchitecture(settlements,source),{camera,controls,renderer}=world,canvas=renderer.domElement,ray=new T.Raycaster(),pointer=new T.Vector2(),reduced=matchMedia('(prefers-reduced-motion: reduce)'),keys=new Set(),removeDoor=nav.addDynamic(art.entry.proxy);nav.add(art.root);nav.add(art.telescope);
 let leafCheck=0,leafBlocked=false;const leafOccluders=[];source.traverse(o=>{if(o.isMesh&&/_canopy$/.test(o.name))leafOccluders.push(o);});
 let active=false,az=41,el=55,target=0,recording=false,progress=0,pending=false,session=0,saved=null,selected=false,down=null,drag=null,last=performance.now(),scan=0,disposed=false,enabled=true,previous=null,spinning=true,seen=market.store.snapshot().stars.seen;
 const make=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;},button=(text,fn)=>{const b=make('button',text);b.type='button';b.onclick=fn;return b;};
 const panel=make('section');panel.className='star-hall-panel';panel.hidden=true;panel.innerHTML='<header><strong>星辰馆 · 藏星室</strong><button aria-label="退出星辰馆近观">×</button></header><div class="star-hall-actions"></div><p>点击星仪、观测册、壁灯与门扇，也可以互动。</p>';
 const dialog=make('dialog');dialog.className='star-hall-dialog';dialog.setAttribute('aria-labelledby','star-journal-title');dialog.innerHTML='<header><div><small>浮空群岛 · 观星人的藏书</small><h2 id="star-journal-title">星辰馆</h2></div><button aria-label="关闭观星手册">×</button></header><div class="star-hall-body"></div>';
 const scope=make('section');scope.className='star-scope';scope.hidden=true;scope.setAttribute('aria-label','望远镜观测');scope.innerHTML='<div class="star-reticle" aria-hidden="true"><i></i><b></b></div><div class="star-scope-card"><header><div><small>观测岛 · 黄铜望远镜</small><h2>寻找夜空中的星图</h2></div><button aria-label="离开望远镜">×</button></header><nav aria-label="待观测星图"></nav><p class="star-target"></p><label>方位 <input data-star-axis="az" type="range" min="-180" max="180" step="0.1" aria-label="望远镜方位"></label><label>仰角 <input data-star-axis="el" type="range" min="25" max="85" step="0.1" aria-label="望远镜仰角"></label><div class="star-fine" aria-label="望远镜微调"></div><p class="star-reading"></p><progress max="1" value="0" aria-label="星图记录进度"></progress><button data-star-record>记录当前星图 · E</button><p class="star-status" role="status" aria-live="polite"></p><small>方向键 / 拖动微调 · 稳定观测 1.6 秒 · Esc 返回</small></div>';
 const hint=button('星辰馆 · 观测与藏星',directory);hint.className='star-hall-hint';hint.hidden=true;document.body.append(panel,dialog,scope,hint);
 const link=button('星辰馆',()=>{const map=document.querySelector('.atlas-map');if(map.open){map.addEventListener('close',directory,{once:true});map.close();}else directory();});link.dataset.starHall='true';document.querySelector('[data-region-card=aether]>div:last-child')?.append(link);
 function paintBook(){
  const map=art.book.material.map,ctx=map.image.getContext('2d');paintFolioBase(ctx);ctx.fillStyle='#493f31';ctx.textAlign='center';ctx.font='37px serif';ctx.fillText(art.book.name,305,116,485);
  STAR_CHARTS.forEach((c,i)=>{const [x,y,k]=[[305,380,42],[895,245,32],[895,520,32]][i],done=seen.includes(c.id);ctx.strokeStyle=done?'#5b675b':'#95866d';ctx.lineWidth=done?5:3;ctx.setLineDash(done?[]:[8,9]);for(const[a,b]of c.edges){ctx.beginPath();ctx.moveTo(x+c.points[a][0]*k,y-c.points[a][1]*k);ctx.lineTo(x+c.points[b][0]*k,y-c.points[b][1]*k);ctx.stroke();}ctx.setLineDash([]);ctx.fillStyle='#695535';for(const[p,q]of c.points){ctx.beginPath();ctx.arc(x+p*k,y-q*k,done?7:4,0,Math.PI*2);ctx.fill();}ctx.font='30px serif';ctx.fillText(c.name,x,y+107);ctx.font='24px serif';ctx.fillText(c.az+'° / '+c.el+'°',x,y+143);});
  ctx.font='26px serif';ctx.fillText('已收录 '+seen.length+' / 3',305,689);map.needsUpdate=true;
 }paintBook();
 const sky=new T.Group();sky.name='群岛 · 三幅原创星图';world.scene.add(sky);const skyMaterials=[];function direction(a,e){const r=Math.PI/180;return new T.Vector3(Math.sin(a*r)*Math.cos(e*r),Math.sin(e*r),-Math.cos(a*r)*Math.cos(e*r));}
 const starCanvas=document.createElement('canvas');starCanvas.width=64;starCanvas.height=64;const starCtx=starCanvas.getContext('2d'),gradient=starCtx.createRadialGradient(32,32,0,32,32,30);gradient.addColorStop(0,'#ffffff');gradient.addColorStop(.18,'#ffffff');gradient.addColorStop(.48,'#ffffff88');gradient.addColorStop(1,'#ffffff00');starCtx.fillStyle=gradient;starCtx.fillRect(0,0,64,64);const starMap=new T.CanvasTexture(starCanvas);
 for(const chart of STAR_CHARTS){const pts=chart.points.map(([x,y])=>direction(chart.az+x/Math.cos(chart.el*Math.PI/180),chart.el+y).multiplyScalar(900)),g=new T.BufferGeometry().setFromPoints(pts),mat=new T.PointsMaterial({color:chart.color,size:7,map:starMap,sizeAttenuation:false,transparent:true,opacity:0,depthWrite:false,fog:false});const stars=new T.Points(g,mat);stars.frustumCulled=false;sky.add(stars);skyMaterials.push({mat,id:chart.id,lines:false});const segments=[];for(const[a,b]of chart.edges)segments.push(pts[a],pts[b]);const lm=new T.LineBasicMaterial({color:chart.color,transparent:true,opacity:0,depthWrite:false,fog:false}),lines=new T.LineSegments(new T.BufferGeometry().setFromPoints(segments),lm);sky.add(lines);skyMaterials.push({mat:lm,id:chart.id,lines:true});}
 function renderPanel(){panel.hidden=!selected;if(!selected)return;const body=panel.querySelector('.star-hall-actions');body.replaceChildren(button('外观',()=>focus(false)),button('进入藏星室',()=>focus(true)),button(art.entry.open?'关上木门':'打开木门',()=>{art.entry.open=!art.entry.open;renderPanel();}),button(art.record.lampsOn?'熄下壁灯':'点亮壁灯',()=>{art.record.lampsOn=!art.record.lampsOn;renderPanel();}),button('翻开观测册',journal),button(spinning?'暂停三环星仪':'转动三环星仪',()=>{spinning=!spinning;renderPanel();}),button('到观测岛看望远镜',instrument));}
 function closeDialog(){if(dialog.open)dialog.close();}dialog.querySelector('header button').onclick=closeDialog;dialog.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))restoreCameraInput(world,enabled);(previous?.isConnected?previous:canvas).focus({preventScroll:true});});
 function show(title,kind){stop();world.atlas.resources.cancel();world.atlas.town.clear();gathering.cancel({clearSelection:true});world.cancelCameraMotion();dialog.dataset.view=kind;dialog.querySelector('h2').textContent=title;const body=dialog.querySelector('.star-hall-body');body.replaceChildren();if(!dialog.open){previous=document.activeElement;enabled=cameraInputEnabled(world);controls.enabled=false;dialog.showModal();}return body;}
 const handoff=fn=>{dialog.addEventListener('close',fn,{once:true});closeDialog();};
 function directory(){if(isBlocked())return false;const body=show('星辰馆与观测岛','directory');body.append(make('p','林间八角书屋保存着群岛的星图，远处浮岛上的望远镜可以转向夜空。两处都在眼前这片世界中。'),button('进入星辰馆',()=>handoff(()=>focus(true))),button('看星辰馆外观',()=>handoff(()=>focus(false))),button('到望远镜旁',()=>handoff(instrument)),button('翻开夜空观测册',journal));return true;}
 function focus(interior=true){if(isBlocked())return false;world.atlas.travel('aether');const ok=buildings.focus(art.record,interior,{lightScale:.3});selected=ok;renderPanel();return ok;}
 function instrument(){if(isBlocked())return false;world.atlas.travel('aether');world.cancelCameraMotion();camera.position.copy(art.telescope.localToWorld(new T.Vector3(-5.8,8.6,5.6)));controls.target.copy(art.telescope.localToWorld(new T.Vector3(0,4.8,0)));camera.lookAt(controls.target);controls.update();hint.textContent='使用黄铜望远镜';return true;}
 function journal(){const body=show('夜空观测册','journal');seen=market.store.snapshot().stars.seen;body.append(make('p',`已收录 ${seen.length} / 3 幅星图。对准亮星并完成观测后，馆内对应星环会发光。`));for(const c of STAR_CHARTS){const row=make('article');row.dataset.chart=c.id;row.append(make('h3',c.name+' · '+(seen.includes(c.id)?'已收录':'待观测')),make('p',c.text),make('p',`方位 ${c.az}° · 仰角 ${c.el}°`),button('去观测这幅星图',()=>handoff(()=>{instrument();start(c.id);})));body.append(row);}body.append(button('返回星辰馆',()=>handoff(()=>focus(true))),make('small','这是群岛世界的原创星图与故事。观测记录保存在当前浏览器。'));}
 function stop(restore=true){if(!active)return;active=false;session++;recording=false;progress=0;keys.clear();drag=null;scope.hidden=true;delete document.body.dataset.starObserving;restoreCameraInput(world,saved.enabled);controls.minDistance=saved.min;controls.enableDamping=saved.damping;camera.clearViewOffset();if(saved.view?.enabled)camera.setViewOffset(saved.view.fullWidth,saved.view.fullHeight,saved.view.offsetX,saved.view.offsetY,saved.view.width,saved.view.height);camera.fov=saved.fov;camera.updateProjectionMatrix();environment.setNight(saved.night);if(restore){const delta=art.telescope.getWorldPosition(new T.Vector3()).sub(saved.anchor);camera.position.copy(saved.eye).add(delta);controls.target.copy(saved.target).add(delta);camera.lookAt(controls.target);controls.update();}saved=null;canvas.focus({preventScroll:true});}
 function start(id=STAR_CHARTS[target].id){if(active||isBlocked())return false;world.atlas.resources.cancel();world.atlas.town.clear();gathering.cancel({clearSelection:true});world.cancelCameraMotion();buildings.close();selected=false;renderPanel();target=Math.max(0,STAR_CHARTS.findIndex(c=>c.id===id));const c=STAR_CHARTS[target];az=c.az+9;el=c.el-3;saved={eye:camera.position.clone(),target:controls.target.clone(),anchor:art.telescope.getWorldPosition(new T.Vector3()),fov:camera.fov,min:controls.minDistance,enabled:cameraInputEnabled(world),damping:controls.enableDamping,night:environment.night,view:camera.view?{...camera.view}:null};controls.enabled=false;controls.enableDamping=false;controls.minDistance=.01;active=true;leafCheck=0;session++;environment.setNight(true);document.body.dataset.starObserving='true';scope.hidden=false;scope.querySelector('.star-status').textContent='转动镜筒，让星图中心落入准星。';refreshScope();scope.querySelector('header button').focus();return true;}
 function aim(a,e){az=((a+180)%360+360)%360-180;el=T.MathUtils.clamp(e,25,85);}
 function readings(){const chart=STAR_CHARTS[target],error=angularError(az,el,chart),origin=art.objective.getWorldPosition(new T.Vector3()),end=origin.clone().addScaledVector(direction(az,el),200);if(performance.now()-leafCheck>200){leafCheck=performance.now();ray.set(origin,direction(az,el));ray.far=200;leafBlocked=ray.intersectObjects(leafOccluders,false).length>0;}const occluded=leafBlocked||nav.obstructed(origin,end,.015);return{error,occluded,aligned:error<=STAR_TOLERANCE&&!occluded&&environment.nightBlend>.8};}
 function refreshScope(){const c=STAR_CHARTS[target];scope.querySelectorAll('[data-chart]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.chart===c.id)));scope.querySelector('.star-target').textContent=`${c.name} · 目标方位 ${c.az}° / 仰角 ${c.el}°`;scope.querySelector('[data-star-axis=az]').value=az;scope.querySelector('[data-star-axis=el]').value=el;}
 for(const c of STAR_CHARTS){const b=button(c.name,()=>{target=STAR_CHARTS.indexOf(c);recording=false;progress=0;refreshScope();});b.dataset.chart=c.id;scope.querySelector('nav').append(b);}
 for(const[id,text,a,e]of [['left','←',-.5,0],['right','→',.5,0],['up','↑',0,.5],['down','↓',0,-.5]]){const b=button(text,()=>{aim(az+a,el+e);refreshScope();});b.dataset.starStep=id;b.setAttribute('aria-label','微调'+({left:'向左',right:'向右',up:'向上',down:'向下'}[id]));scope.querySelector('.star-fine').append(b);}
 scope.querySelectorAll('input').forEach(i=>{let pointerId=null;const apply=()=>{aim(i.dataset.starAxis==='az'?+i.value:az,i.dataset.starAxis==='el'?+i.value:el);refreshScope();};i.oninput=apply;const at=e=>{const box=i.getBoundingClientRect(),t=T.MathUtils.clamp((e.clientX-box.left-7)/(box.width-14),0,1);i.value=+i.min+t*(+i.max-+i.min);apply();};i.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();pointerId=e.pointerId;i.setPointerCapture(e.pointerId);i.focus({preventScroll:true});at(e);};i.onpointermove=e=>{if(pointerId===e.pointerId){e.preventDefault();at(e);}};i.onpointerup=e=>{if(pointerId===e.pointerId){at(e);pointerId=null;i.releasePointerCapture(e.pointerId);}};i.onpointercancel=()=>pointerId=null;});
 function record(){if(!active||pending||recording||!readings().aligned||seen.includes(STAR_CHARTS[target].id))return false;recording=true;progress=0;scope.querySelector('.star-status').textContent='保持镜筒稳定，正在描摹亮星…';return true;}
 async function finish(){const token=session,id=STAR_CHARTS[target].id;recording=false;pending=true;let result;try{const run=()=>{if(disposed||!active||token!==session)return null;market.store.reload();return market.store.recordStar(id);};result=navigator.locks?await navigator.locks.request(MARKET_KEY,run):run();}catch{result={ok:false,message:'记录未保存，请重试。'};}pending=false;seen=market.store.snapshot().stars.seen;paintBook();if(active&&token===session)scope.querySelector('.star-status').textContent=result?.message||'观测已取消。';}
 scope.querySelector('[data-star-record]').onclick=record;scope.querySelector('header button').onclick=()=>stop();panel.querySelector('header button').onclick=()=>{clear();buildings.close();};
 function clear(){stop();selected=false;panel.hidden=true;hint.hidden=true;closeDialog();down=null;}
 function useAction(object){for(let o=object;o;o=o.parent){const action=o.userData.starAction;if(action==='telescope'){start();return true;}if(action==='journal'){journal();return true;}if(action==='orrery'){spinning=!spinning;renderPanel();say(spinning?'三环星仪开始转动。':'三环星仪停在当前刻度。');return true;}if(action==='lamps'){art.record.lampsOn=!art.record.lampsOn;renderPanel();return true;}if(o===art.entry.root){art.entry.open=!art.entry.open;renderPanel();return true;}}return false;}
 function pointerDown(e){if(e.button!==0)return;if(active){drag={id:e.pointerId,x:e.clientX,y:e.clientY,a:az,e:el};canvas.setPointerCapture(e.pointerId);e.preventDefault();e.stopImmediatePropagation();}else down=[e.clientX,e.clientY];}
 function pointerMove(e){if(active&&drag?.id===e.pointerId){aim(drag.a-(e.clientX-drag.x)*.05,drag.e+(e.clientY-drag.y)*.05);refreshScope();e.preventDefault();e.stopImmediatePropagation();}}
 function pointerUp(e){if(active){drag=null;e.preventDefault();e.stopImmediatePropagation();return;}const p=down;down=null;if(!p||e.button!==0||Math.hypot(e.clientX-p[0],e.clientY-p[1])>6||isBlocked())return;const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);ray.far=50;const hit=ray.intersectObjects([art.root,art.telescope],true).find(h=>{for(let o=h.object;o;o=o.parent)if(!o.visible)return false;return true;});if(!hit)return;let o=hit.object,isDoor=false;for(;o;o=o.parent)if(o===art.entry.root)isDoor=true;if(nav.obstructed(camera.position,hit.point.clone().lerp(camera.position,.02),.005,null,isDoor?art.entry.proxy:null))return;if(hit.distance<=10&&useAction(hit.object))return;queueMicrotask(()=>focus(false));}
 const release=()=>{down=null;drag=null;keys.clear();},blur=()=>{release();stop();},key=e=>{if(active){if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();stop();return;}if(e.code==='KeyM'){e.preventDefault();e.stopImmediatePropagation();stop();world.atlas.openMap();return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyE'].includes(e.code)&&e.target.tagName!=='INPUT'){e.preventDefault();e.stopImmediatePropagation();if(e.code==='KeyE'){if(!e.repeat)record();}else keys.add(e.code);return;}if(['KeyB','KeyJ','KeyK','KeyH'].includes(e.code))stop();}else if(e.code==='Escape'&&!dialog.open){selected=false;panel.hidden=true;}},keyup=e=>keys.delete(e.code),outside=e=>{if(active&&e.target!==canvas&&!scope.contains(e.target))stop();},visibility=()=>{if(document.hidden)blur();},storage=e=>{if(e.key===MARKET_KEY){market.store.reload();seen=market.store.snapshot().stars.seen;paintBook();if(dialog.open&&dialog.dataset.view==='journal')journal();}};
 canvas.addEventListener('pointerdown',pointerDown,true);canvas.addEventListener('pointermove',pointerMove,true);canvas.addEventListener('pointerup',pointerUp,true);canvas.addEventListener('pointercancel',release);window.addEventListener('keydown',key,true);window.addEventListener('keyup',keyup,true);window.addEventListener('blur',blur);window.addEventListener('storage',storage);document.addEventListener('visibilitychange',visibility);document.addEventListener('click',outside,true);
 function update(){const now=performance.now(),dt=Math.min(.075,(now-last)/1000);last=now;art.entry.angle=reduced.matches?(art.entry.open?-1.48:0):T.MathUtils.damp(art.entry.angle,art.entry.open?-1.48:0,7,dt);art.entry.root.rotation.y=art.entry.angle;const near=camera.position.distanceTo(art.root.getWorldPosition(new T.Vector3()))<25;art.lamps.forEach(l=>l.intensity=near&&art.record.lampsOn?2.5:0);art.record.filament.emissiveIntensity=art.record.lampsOn?.35:0;for(const r of art.rings){const done=seen.includes(r.id);r.orb.material.emissiveIntensity=done?2:0;if(spinning&&!reduced.matches)r.root.rotation.y+=dt*(done?.25:.06);}
 sky.position.copy(camera.position);skyMaterials.forEach(s=>s.mat.opacity=environment.nightBlend*(s.lines?(active&&s.id===STAR_CHARTS[target].id?.45:seen.includes(s.id)?.18:0):.95));
 if(active){aim(az+((keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0))*8*dt,el+((keys.has('ArrowUp')?1:0)-(keys.has('ArrowDown')?1:0))*8*dt);art.yaw.rotation.y=-az*Math.PI/180;art.pitch.rotation.x=el*Math.PI/180;art.telescope.updateWorldMatrix(true,true);camera.position.copy(art.objective.getWorldPosition(new T.Vector3()));controls.target.copy(camera.position).addScaledVector(direction(az,el),10);camera.lookAt(controls.target);if(innerWidth<700)camera.setViewOffset(innerWidth,innerHeight,0,innerHeight*.18,innerWidth,innerHeight);else camera.clearViewOffset();sky.position.copy(camera.position);const r=readings();if(recording){if(!r.aligned){recording=false;progress=0;scope.querySelector('.star-status').textContent='镜筒偏离了目标，重新对准后再记录。';}else{progress=Math.min(1,progress+dt/STAR_HOLD_SECONDS);if(progress>=1)finish();}}if(now-scan>100){scan=now;refreshScope();scope.querySelector('.star-reading').textContent=`当前 ${az.toFixed(1)}° / ${el.toFixed(1)}° · ${r.occluded?'视线受遮挡':environment.nightBlend<.8?'等待夜色降临':r.aligned?'已对准':'偏差 '+r.error.toFixed(1)+'°'}`;scope.querySelector('[data-star-record]').disabled=pending||recording||!r.aligned||seen.includes(STAR_CHARTS[target].id);scope.querySelector('progress').value=progress;scope.dataset.aligned=String(r.aligned);scope.dataset.chart=STAR_CHARTS[target].id;}hint.hidden=true;return;}
 if(buildings.selected===art.record.id&&!selected){selected=true;renderPanel();}else if(selected&&buildings.selected!==art.record.id){selected=false;panel.hidden=true;}
 if(isBlocked()||selected||document.body.dataset.visitorHidden==='true'){hint.hidden=true;return;}const tp=art.telescope.localToWorld(new T.Vector3(0,7.2,0)),useScope=camera.position.distanceTo(tp)<14,p=useScope?tp:art.root.localToWorld(new T.Vector3(0,4,1)),v=p.clone().project(camera);hint.textContent=useScope?'使用黄铜望远镜':'星辰馆 · 观测与藏星';hint.onclick=useScope?()=>start():directory;hint.hidden=p.distanceTo(camera.position)>40||v.z< -1||v.z>1||Math.abs(v.x)>.78||Math.abs(v.y)>.7;if(!hint.hidden){hint.style.left=T.MathUtils.clamp((v.x*.5+.5)*innerWidth,125,innerWidth-125)+'px';hint.style.top=T.MathUtils.clamp((-v.y*.5+.5)*innerHeight,110,innerHeight-230)+'px';}}
 return{architecture:art,update,clear,stop,start,record,focus,instrument,journal,directory,get active(){return active;},get fov(){return innerWidth<700?18:14;},stats:()=>({active,az,el,target:STAR_CHARTS[target].id,recording,progress,pending,seen:market.store.snapshot().stars.seen,spinning,door:art.entry.open,anchor:art.telescope.getWorldPosition(new T.Vector3()).toArray(),objective:art.objective.getWorldPosition(new T.Vector3()).toArray(),readings:active?readings():null}),dispose(){disposed=true;clear();removeDoor();art.dispose();starMap.dispose();sky.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});sky.removeFromParent();[panel,dialog,scope,hint,link].forEach(n=>n.remove());canvas.removeEventListener('pointerdown',pointerDown,true);canvas.removeEventListener('pointermove',pointerMove,true);canvas.removeEventListener('pointerup',pointerUp,true);canvas.removeEventListener('pointercancel',release);window.removeEventListener('keydown',key,true);window.removeEventListener('keyup',keyup,true);window.removeEventListener('blur',blur);window.removeEventListener('storage',storage);document.removeEventListener('visibilitychange',visibility);document.removeEventListener('click',outside,true);}};
}
