import {cameraInputEnabled,restoreCameraInput} from './camera-input.js';
import * as T from 'three';
import {TRADES,FISH,TOWN_KEY} from './town-content.js';
import {createTownStore} from './town-store.js';
import {makeTrade,makeHearth,makeFishing,makeInnInterior} from './town-props.js';
import {RECIPES,PROFESSIONS,professionLevel,recipeDuration} from './profession-content.js';
import {GOODS} from './market-content.js';
import {makeKitchen} from './kitchen-props.js';
import './town-life.css';

export function createTownLife(world,{settlements,buildings,gathering,nav,isBlocked,say}){
 const {camera,controls,renderer}=world,canvas=renderer.domElement,store=createTownStore(),records=[],seen=new Set(),extras=[],ray=new T.Raycaster(),ndc=new T.Vector2(),reduced=matchMedia('(prefers-reduced-motion: reduce)');
 let hovered=null,down=null,lastScan=0,task=null,previousFocus=null,enabled=true,view='ledger',activeRecord=null,disposed=false;
 const dialog=document.createElement('dialog');dialog.className='town-dialog';dialog.setAttribute('aria-labelledby','town-title');dialog.innerHTML='<header><div><small>五境 · 风物与手艺</small><h2 id="town-title"></h2></div><button data-close aria-label="关闭城镇手册">×</button></header><div class="town-body"></div><p class="town-feedback" role="status" aria-live="polite"></p><footer><button data-ledger>城镇手册</button><span>此浏览器的私人旅程</span></footer>';
 const hint=document.createElement('button');hint.className='town-hint';hint.hidden=true;
 const activity=document.createElement('section');activity.className='town-activity';activity.hidden=true;activity.innerHTML='<p role="status" aria-live="polite"></p><progress max="1"></progress><div><button data-primary>收竿</button><button data-cancel>收起 · Esc</button></div>';
 document.body.append(dialog,hint,activity);const body=dialog.querySelector('.town-body'),feedback=dialog.querySelector('.town-feedback');
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const button=(text,fn,disabled=false)=>{const b=el('button',text);b.type='button';b.onclick=fn;b.disabled=disabled;return b;};
 function show(title,kind){world.atlas?.resources?.cancel();cancel();gathering.cancel({clearSelection:true});world.cancelCameraMotion();view=kind;dialog.dataset.view=kind;dialog.querySelector('h2').textContent=title;body.replaceChildren();feedback.textContent='';dialog.querySelector('[data-ledger]').hidden=kind==='ledger';if(!dialog.open){previousFocus=document.activeElement;enabled=cameraInputEnabled(world);controls.enabled=false;dialog.showModal();}dialog.querySelector('[data-close]').focus();}
 function close(){if(dialog.open)dialog.close();}
 // The native close event is asynchronous. Do not restore controls over a
 // newly-started timed action, or over another open dialog.
 function restore(){if(!task&&!document.querySelector('dialog[open]'))restoreCameraInput(world,enabled);}
 dialog.addEventListener('close',()=>{restore();if(!task)(previousFocus?.isConnected?previousFocus:canvas).focus({preventScroll:true});});
 dialog.querySelector('[data-close]').onclick=close;dialog.querySelector('[data-ledger]').onclick=showLedger;
 function status(saved,message){feedback.textContent=message+(saved?'':' 当前浏览器未能写入存档，刷新后可能丢失。');}
 function showLedger(){show('城镇手册','ledger');const state=store.snapshot();body.append(el('p','炉火旁歇脚，水岸边垂钓。循着手艺，认识五境的日常。','town-intro'));const list=el('ol',undefined,'town-list');
  for(const t of TRADES){const r=records.find(r=>r.id===t.id),li=el('li');li.append(el('small',t.place),el('h3',t.name),el('p',`${state.crafted.includes(t.id)?'已制成 '+t.craft:'学习 '+t.craft} · ${state.visited.includes(t.id)?'已到访':'未到访'}`));const b=button(r?'循路前往':'展开城镇并前往',()=>focus(t.id));li.append(b);list.append(li);}body.append(list);
  const resting=el('div',undefined,'town-links');resting.append(button('到旅舍炉火旁',()=>focus('hearth')),button('到晨露水岸垂钓',()=>focus('fishing')),button('到旅舍厨房',()=>focus('kitchen')));body.append(resting);resting.append(button('布置旅人客房',()=>{dialog.addEventListener('close',()=>world.atlas.housing.open(),{once:true});close();}));resting.append(button('前往山城市集',()=>{dialog.addEventListener('close',()=>world.atlas.market.showDirectory(),{once:true});close();}));
  const commission=el('section',undefined,'town-commission');commission.append(el('h3','匠人的巡礼'),el('p',`各地制作一件风物，替旅舍补齐五境工艺收藏。${state.crafted.length} / 5`));if(state.commission)commission.append(el('p','已完成 · 五境匠心纹章已挂在旅舍炉边。'));else{const b=button('交付巡礼记录',()=>{const saved=store.claim();sync();showLedger();status(saved,'巡礼完成。你的纹章已陈列在山风旅舍。');});b.disabled=state.crafted.length!==5;commission.append(b);}body.append(commission);
  const skills=el('section',undefined,'town-commission');skills.append(el('h3','材料与配方'));const ps=world.atlas.market.store.snapshot().professions;for(const [id,name]of Object.entries(PROFESSIONS))skills.append(el('p',name+' · 熟练 '+professionLevel(ps.xp[id])+' / 5'));skills.append(button('查看原料产地',()=>{dialog.addEventListener('close',()=>world.atlas.resources.showDirectory(),{once:true});close();}));skills.append(el('p','在各地工坊学习加工，在厨房烹饪；铜锭、玻璃、木料可以共同制作客房陈设。'),button(ps.kit?'学徒材料包已领取':'领取一次学徒材料包',()=>{const result=world.atlas.market.store.claimKit();gathering.refreshBag();showLedger();status(result.saved!==false,result.message);},ps.kit));body.append(skills);
  const fish=el('details');fish.append(el('summary','水岸鱼谱'));for(const f of FISH)fish.append(el('p',`${f.name} · ${state.fish[f.id]||0} 尾记录`));body.append(fish);
 }
 function showTrade(r){activeRecord=r;store.visit(r.id);show(r.trade.name,'trade');const state=store.snapshot(),known=state.crafted.includes(r.id),available=gathering.store.snapshot().items[r.id+'-flower']>0;body.append(el('small',r.trade.place),el('p',r.trade.text),el('h3',r.trade.craft),el('p',`纹样参考：${r.trade.flower} · ${available?'已收录':'待采集'}`),el('p','首次采得当地花朵后，便能学习这件工艺。材料由工坊提供，保留行囊中的花。','town-note'));
  const delivery=world.atlas.market?.store,deliveryState=delivery?.snapshot();if(deliveryState?.contract==='active'){const delivered=deliveryState.delivered.includes(r.id);body.append(button(delivered?'本地货单已交付':'交付驿站货单',()=>{if(!reachable(r)){feedback.textContent='请先回到工艺台旁。';return;}const result=delivery.deliver(r.id);showTrade(r);status(result.saved!==false,result.message);},delivered));}
  body.append(button('查看材料配方',()=>showRecipes(r)));
  const b=button(known?'再做一次':'开始制作 · 3 秒',()=>{if(!reachable(r)){feedback.textContent='请先回到工艺台旁。';return;}close();begin('craft',r,3000);});b.disabled=!available;body.append(b);
  if(known){const visible=state.display[r.id]!==false;body.append(button(visible?'收起台上的成品':'将成品摆在台上',()=>{const saved=store.display(r.id,!visible);sync();showTrade(r);status(saved,visible?'成品已收入工艺收藏。':'成品已摆在台上。');}));}
 }
 function showRecipes(r){const profession=r.profession||r.id;activeRecord=r;show(r.name||(r.kind==='kitchen'?'山风旅舍厨房':PROFESSIONS[profession]+' · 材料配方'),'recipes');const inventory=world.atlas.market.store,state=inventory.snapshot(),level=professionLevel(state.professions.xp[profession]),name=id=>GOODS.find(g=>g.id===id)?.name||id;
 body.append(el('p','熟练 '+level+' / 5 · 每完成两次加工提升一级，最高五级。每级提速 5%，最多 20%。'),el('p','材料在完成时才消耗，取消或离开不扣材料。需要随身携带，保管库内的物品须先取回。','town-note'));
 for(const rec of RECIPES.filter(rec=>rec.site===profession&&(r.recipeIds?r.recipeIds.includes(rec.id):!['charcoal','flour'].includes(rec.id)))){const row=el('section',undefined,'town-recipe');row.dataset.recipe=rec.id;row.append(el('h3',rec.name),el('small','熟练 '+rec.level+' · 已制作 '+(state.professions.made[rec.id]||0)+' 次'));const list=el('ul');for(const[id,n]of Object.entries(rec.input))list.append(el('li',name(id)+' × '+n+' · 行囊 '+state.bag[id]));row.append(list,el('p','成品：'+Object.entries(rec.output).map(([id,n])=>name(id)+' × '+n).join('、')));const check=inventory.recipeStatus(rec.id);row.append(button('制作这份配方',()=>{if(!reachable(r)){feedback.textContent='请先回到工作台旁。';return;}close();begin('produce',r,recipeDuration(inventory.snapshot().professions.xp[profession],inventory.effect('bread')>0),rec);},!check.ok));if(!check.ok)row.append(el('small',check.message));body.append(row);}
 if(r.id==='valley'||r.id==='kitchen'){const id=r.id==='valley'?'charcoal-kiln':'mill';body.append(button(r.id==='valley'?'到屋外炭窑烧制木炭':'到厨房石磨磨粉',()=>{dialog.addEventListener('close',()=>focus(id),{once:true});close();}));}
 body.append(button('寻找配方原料',()=>{dialog.addEventListener('close',()=>world.atlas.resources.showDirectory(),{once:true});close();}),el('p','可在原料产地采收，也可到杂货铺与药房补充。原木可制炭，山麦可磨粉。','town-note'));if(r.kind==='kitchen')body.append(el('p','面包：制作加快；松针茶：延长收竿窗口。成品收入 B 行囊后可使用，效果持续五分钟。'));
 }
 function showHearth(r){activeRecord=r;show('山风旅舍','hearth');const state=store.snapshot();body.append(el('p','拱炉里留着一束干木。雨雪之后，也能在这里看一会儿炉火。'),button(state.hearth?'熄下炉火':'添柴点火',()=>{const saved=store.hearth(!state.hearth);sync();showHearth(r);status(saved,state.hearth?'炉膛渐暗。':'火焰重新照亮炉石。');}),button('在炉边歇一会儿',()=>{if(!reachable(r)){feedback.textContent='请先回到炉火旁。';return;}close();begin('rest',r,6000);}),button('查看匠人巡礼',showLedger));if(state.rested)body.append(el('small','已经在这间旅舍留下歇脚的记忆。'));}
 function showFishing(r){activeRecord=r;show('晨露垂钓','fishing');body.append(el('p','向亭外的湖水抛下鱼线，等待浮漂轻沉。看到提示后收竿，太早或太迟都不会记作收获。'),el('p','一竿约 5—8 秒；咬钩后通常有 4 秒收竿，凝神时延长至 6 秒。可随时按 Esc 取消。','town-note'),button('抛竿',()=>{if(!reachable(r)){feedback.textContent='请先回到水岸钓具旁。';return;}close();begin('fish',r,5000+Math.random()*3000);}));for(const f of FISH)body.append(el('p',`${f.name} · 已记录 ${store.snapshot().fish[f.id]||0} 尾`));}
 function activate(r){if(isBlocked()||!reachable(r))return false;hovered=r;gathering.cancel({clearSelection:true});if(r.kind==='trade')showTrade(r);else if(r.kind==='hearth')showHearth(r);else if((r.kind==='kitchen'||r.kind==='workshop'))showRecipes(r);else showFishing(r);return true;}
 function begin(kind,r,duration,recipe){if(task||disposed)return;const savedView={camera:camera.position.clone(),target:controls.target.clone()};if(kind==='fish'){const eye=r.root.localToWorld(new T.Vector3(.15,2.8,-.45)),target=r.root.localToWorld(new T.Vector3(.45,-.35,-3.2));if(!nav.obstructed(eye,eye,.15)){camera.position.copy(eye);controls.target.copy(target);camera.lookAt(target);controls.update();}}task={kind,r,recipe,savedView,start:performance.now(),duration,stage:'waiting',camera:camera.position.clone(),target:controls.target.clone()};document.body.dataset.townBusy='true';controls.enabled=false;activity.hidden=false;hint.hidden=true;activity.querySelector('p').textContent=kind==='fish'?'鱼线落在水面，等待浮漂……':kind==='rest'?'在炉火旁歇一会儿……':`正在${recipe?.name||'制作'+r.trade.craft}……`;activity.querySelector('[data-primary]').hidden=kind!=='fish';activity.querySelector('[data-primary]').disabled=false;activity.querySelector('progress').value=0;if(kind==='fish'||kind==='produce')r.prop.setActive?.(true);activity.querySelector('[data-cancel]').focus();}
 function cancel(message){const old=task;if(!old)return;task=null;if(old.kind==='fish'&&camera.position.distanceTo(old.camera)<.7){camera.position.copy(old.savedView.camera);controls.target.copy(old.savedView.target);camera.lookAt(controls.target);controls.update();}old.r.prop.setActive?.(false);delete document.body.dataset.townBusy;activity.hidden=true;restore();if(message)say(message);canvas.focus({preventScroll:true});}
 function reel(){if(task?.kind!=='fish')return;const r=task.r;if(task.stage!=='bite'){cancel('收竿早了些，鱼还没靠近。');return;}if(performance.now()>task.start+task.duration+(task.biteWindow||4000)){cancel('鱼已经松开了钩。');return;}const count=Object.values(store.snapshot().fish).reduce((a,b)=>a+b,0),f=FISH[count%FISH.length],saved=store.catchFish(f.id);cancel();showFishing(r);status(saved,`钓到${f.name}。已记入水岸鱼谱，鱼儿已放回湖中。`);}
 activity.querySelector('[data-primary]').onclick=reel;activity.querySelector('[data-cancel]').onclick=()=>cancel('已收起手边的事。');
 function sync(){const state=store.snapshot();for(const r of records){if(r.kind==='trade')r.prop.setDisplay(state.crafted.includes(r.id)&&state.display[r.id]!==false);if(r.kind==='hearth')r.prop.setLit(state.hearth);}extras.forEach(p=>p.setAward?.(state.commission));}
 function add(region){if(seen.has(region.id))return;const trade=TRADES.find(t=>t.id===region.id),building=settlements.records.find(r=>r.region===region.id&&r.name.startsWith(trade.match));if(!building)return;seen.add(region.id);const prop=makeTrade(settlements.materials,trade);prop.root.position.fromArray(trade.position);prop.root.rotation.y=trade.yaw;building.root.add(prop.root);
  if(region.id==='forest'){building.root.updateWorldMatrix(true,true);const p=prop.root.getWorldPosition(new T.Vector3()),y=nav.height(p.x,p.z,p.y+5,p.y-5,true);if(y!==null){p.y=y+.035;building.root.worldToLocal(p);prop.root.position.y=p.y;}}
  records.push({id:trade.id,kind:'trade',trade,building,prop,root:prop.root,anchor:prop.anchor});
  if(region.id==='highland'){const prop=makeHearth(settlements.materials);prop.root.position.set(0,.10,-5.65);building.root.add(prop.root);records.push({id:'hearth',kind:'hearth',building,prop,root:prop.root,anchor:prop.anchor});const kitchen=makeKitchen(settlements.materials);kitchen.root.position.set(3.65,.10,.4);kitchen.root.rotation.y=-Math.PI/2;building.root.add(kitchen.root);building.root.updateWorldMatrix(true,true);const kitchenFoot=kitchen.root.getWorldPosition(new T.Vector3()),kitchenFloor=nav.height(kitchenFoot.x,kitchenFoot.z,kitchenFoot.y+.1,kitchenFoot.y-.5);if(kitchenFloor!==null){kitchenFoot.y=kitchenFloor+.002;building.root.worldToLocal(kitchenFoot);kitchen.root.position.y=kitchenFoot.y;}nav.add(kitchen.root);records.push({id:'kitchen',kind:'kitchen',building,prop:kitchen,root:kitchen.root,anchor:kitchen.anchor});
   const dress=makeInnInterior(settlements.materials);building.root.add(dress.root);extras.push(dress);}
  if(region.id==='watercourt'){const b=settlements.records.find(r=>r.region==='watercourt'&&r.name==='西岸会客亭'),prop=makeFishing(settlements.materials);prop.root.position.set(0,.71,1.35);prop.root.rotation.y=Math.PI;b.root.add(prop.root);prop.setWaterLevel(-.7);prop.setActive(false);records.push({id:'fishing',kind:'fishing',building:b,prop,root:prop.root,anchor:prop.anchor});}
  building.root.updateWorldMatrix(true,true);sync();
 }
 function anchor(r){r.root.updateWorldMatrix(true,false);return r.anchor.clone().applyMatrix4(r.root.matrixWorld);}
 function reachable(r){for(let o=r.root;o;o=o.parent)if(!o.visible)return false;const p=anchor(r),s=p.clone().project(camera);return camera.position.distanceTo(p)<13&&s.z>=-1&&s.z<=1&&Math.abs(s.x)<.98&&Math.abs(s.y)<.96&&!nav.obstructed(camera.position,p.clone().lerp(camera.position,.015),.003);}
 let focusRequest=0;
 async function focus(id){const request=++focusRequest,wasOpen=dialog.open;let r=records.find(r=>r.id===id);if(!r){const region=TRADES.find(t=>t.id===id)?.id||({fishing:'watercourt','seed-table':'forest','charcoal-kiln':'valley',mill:'highland',kitchen:'highland',hearth:'highland'})[id];if(region){feedback.textContent='正在展开目的地…';await world.atlas.readyFor(region);if(request!==focusRequest||(wasOpen&&!dialog.open)||disposed)return false;r=records.find(r=>r.id===id);}}if(!r){feedback.textContent='该区域尚未加载，请在地图中重试。';say('该区域尚未加载，请在地图中重试。');return false;}cancel();close();world.atlas.travel(r.building.region);if(!buildings.focus(r.building,!r.outdoor,{lightScale:r.building.region==='aether'?.2:.55}))return false;nav.sync();const target=anchor(r),scale=r.root.getWorldScale(new T.Vector3()).x;
  // Prefer a front three-quarter close-up, but reject blocked eyes and rays.
  let found=false,best=Infinity;for(const [x,y,z]of (r.outdoor?[[1.3,1.9,3.1],[-1.3,1.9,3.1],[0,2.1,3.4]]:[[1.2,1.85,1.8],[-1.2,1.85,1.8],[0,1.9,1.65],[1.55,1.85,2.25],[-1.55,1.85,2.25],[0,2.3,2.6],[0,1.9,1.5],[1,2,1.5]])){const p=r.root.localToWorld(new T.Vector3(x,y,z));if((!r.outdoor&&!buildings.validInteriorEye(p))||nav.obstructed(p,p,.18*scale)||nav.obstructed(p,target.clone().lerp(p,.02),.012))continue;let score=Math.abs(x)*.01;for(const dx of [-.65,0,.65])for(const yy of [.3,1.1,1.7]){const end=r.root.localToWorld(new T.Vector3(dx,yy,.04)).lerp(p,.02);if(nav.obstructed(p,end,.03))score+=1;}if(score<best){best=score;camera.position.copy(p);found=true;}}

  controls.target.copy(target);camera.lookAt(target);controls.update();hovered=r;gathering.cancel({clearSelection:true});say(r.kind==='trade'?'点击工艺台上的工具，或按 E。':r.kind==='hearth'?'点击炉石，点火或歇脚。':r.kind==='workshop'?'点击设备或按 E，查看加工配方。':r.kind==='kitchen'?'点击案板上的面包，查看烹饪配方。':'点击钓具，向湖面抛竿。');return found||reachable(r);
 }
 function hit(e){if(isBlocked())return null;const rect=canvas.getBoundingClientRect();ndc.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(ndc,camera);ray.far=13;let best=null,distance=Infinity;for(const r of records){if(!reachable(r))continue;const h=ray.intersectObject(r.root,true).find(h=>{for(let p=h.object;p;p=p.parent)if(!p.visible)return false;return true;});if(h&&h.distance<distance){distance=h.distance;best=r;}}return best;}
 function pointerDown(e){if(e.button===0)down={x:e.clientX,y:e.clientY};}
 function pointerUp(e){const start=down;down=null;if(!start||e.button!==0||Math.hypot(start.x-e.clientX,start.y-e.clientY)>6)return;const r=hit(e);if(r)queueMicrotask(()=>activate(r));}
 function pointerMove(e){if(!down){const r=hit(e);if(r){hovered=r;gathering.cancel({clearSelection:true});}}}
 function clear(){down=null;hovered=null;hint.hidden=true;cancel();}
 function blur(){down=null;cancel('离开窗口，已暂停手边的事。');}
 function key(e){if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(task&&e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();cancel('已收起手边的事。');}else if(task?.kind==='fish'&&e.code==='KeyE'){e.preventDefault();e.stopImmediatePropagation();reel();}else if(e.code==='KeyK'&&!isBlocked()){e.preventDefault();showLedger();}else if(e.code==='KeyE'&&!hint.hidden&&hovered&&!isBlocked()){e.preventDefault();e.stopImmediatePropagation();activate(hovered);}}
 const storage=e=>{if(e.key!==TOWN_KEY)return;store.reload();sync();if(dialog.open){if(view==='recipes')showRecipes(activeRecord);else if(view==='ledger')showLedger();else if(view==='trade')showTrade(activeRecord);else if(view==='hearth')showHearth(activeRecord);else showFishing(activeRecord);}};
 function visibility(){if(document.hidden)blur();}
 canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointercancel',clear);window.addEventListener('keydown',key,true);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);window.addEventListener('storage',storage);hint.onclick=()=>hovered&&activate(hovered);
 function update(){const now=performance.now();for(const r of records){if(r.kind==='hearth')r.prop.update(now,reduced.matches,camera);else if(r.kind==='fishing')r.prop.update(now,reduced.matches,task?.stage==='bite');else r.prop.update(now,reduced.matches);}
  if(task){hint.hidden=true;if(document.hidden||document.querySelector('dialog[open]')||camera.position.distanceTo(task.camera)>.7||controls.target.distanceTo(task.target)>.7){cancel('视角已离开，手边的事已收起。');return;}const t=now-task.start;activity.querySelector('progress').value=Math.min(1,t/task.duration);
   if(task.kind==='fish'){if(task.stage==='waiting'&&t>=task.duration){task.stage='bite';task.biteWindow=world.atlas.market.store.effect('tea')?6000:4000;activity.querySelector('p').textContent='浮漂下沉了！收竿 · E';activity.dataset.bite='true';}else if(task.stage==='bite'&&t>=task.duration+(task.biteWindow||4000)){delete activity.dataset.bite;cancel('鱼松开了钩，下一竿再来。');}}
   else if(t>=task.duration){const r=task.r,kind=task.kind,recipe=task.recipe;cancel();if(kind==='produce'){const result=world.atlas.market.store.craft(recipe.id);gathering.refreshBag();if(result.ok)r.prop.pulse();showRecipes(r);status(result.saved!==false,result.message);}else if(kind==='craft'){const result=store.craft(r.id,gathering.store.snapshot().items);sync();r.prop.pulse();say(result.ok?`${r.trade.craft}已制成，摆在台上了。${result.saved?'':'本次无法保存。'}`:result.error);}else{const saved=store.rest();say(saved?'炉边歇脚的记忆已留下。':'已歇脚；本次无法保存。');}}return;
  }
  delete activity.dataset.bite;if(isBlocked()||document.body.dataset.visitorHidden==='true'||document.querySelector('.market-hint:not([hidden])')){hint.hidden=true;return;}if(now-lastScan>250){lastScan=now;if(!hovered||!reachable(hovered))hovered=records.filter(reachable).sort((a,b)=>anchor(a).distanceToSquared(camera.position)-anchor(b).distanceToSquared(camera.position))[0]||null;}
  if(!hovered||gathering.stats().selected||!reachable(hovered)){hint.hidden=true;return;}const p=anchor(hovered).project(camera);hint.hidden=false;hint.style.left=T.MathUtils.clamp((p.x*.5+.5)*innerWidth,110,innerWidth-110)+'px';hint.style.top=T.MathUtils.clamp((-p.y*.5+.5)*innerHeight-66,115,innerHeight-230)+'px';hint.textContent=(hovered.trade?.name||hovered.name|| (hovered.kind==='hearth'?'山风炉火':hovered.kind==='kitchen'?'旅舍厨房':'晨露垂钓'))+' · E';
 }
 return{add,registerWorkshop(r){if(!records.some(old=>old.id===r.id))records.push({...r,kind:'workshop',root:r.prop.root,anchor:r.prop.anchor});},update,focus,showLedger,clear,records,store,get busy(){return!!task;},stats:()=>({state:store.snapshot(),task:task?{kind:task.kind,stage:task.stage,recipe:task.recipe?.id,duration:task.duration,biteWindow:task.biteWindow}:null,sites:records.map(r=>({id:r.id,position:anchor(r).toArray(),reachable:reachable(r)}))}),dispose(){disposed=true;cancel();close();records.forEach(r=>r.prop.dispose());extras.forEach(p=>p.dispose());[dialog,hint,activity].forEach(n=>n.remove());canvas.removeEventListener('pointerdown',pointerDown);canvas.removeEventListener('pointerup',pointerUp);canvas.removeEventListener('pointermove',pointerMove);canvas.removeEventListener('pointercancel',clear);window.removeEventListener('keydown',key,true);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('storage',storage);}};
}
