import {cameraInputEnabled,restoreCameraInput} from './camera-input.js';
import * as T from 'three';
import {createValleyTown} from './valley-town-architecture.js';
import {VALLEY_ORDERS} from './valley-town-content.js';
import {GOODS,MARKET_KEY} from './market-content.js';
import './valley-town.css';
export function createValleyTownLife(world,{settlements,nav,buildings,gathering,market,environment,isBlocked,say}){
 const {camera,controls,renderer}=world,canvas=renderer.domElement,ray=new T.Raycaster(),pointer=new T.Vector2(),reduced=matchMedia('(prefers-reduced-motion: reduce)'),removers=[];let art=null,selected=null,room=0,down=null,enabled=true,previous=null,last=performance.now(),bellAt=-Infinity,disposed=false,view='',pending=false,audio=null;
 const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;},button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};
 const dialog=el('dialog');dialog.className='vtown-dialog';dialog.setAttribute('aria-labelledby','vtown-title');dialog.innerHTML='<header><div><small>北境 · 雪松驿镇</small><h2 id="vtown-title"></h2></div><button aria-label="关闭驿镇手册">×</button></header><div class="vtown-body"></div><p role="status" aria-live="polite"></p>';
 const panel=el('section');panel.className='vtown-panel';panel.hidden=true;panel.innerHTML='<header><strong></strong><button aria-label="退出驿镇近观">×</button></header><nav></nav><div class="vtown-actions"></div><p role="status"></p>';
 const hint=button('雪松驿镇 · 走近看看',()=>directory());hint.className='vtown-hint';hint.hidden=true;document.body.append(dialog,panel,hint);
 function close(){if(dialog.open)dialog.close();}dialog.querySelector('header button').onclick=close;dialog.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))restoreCameraInput(world,enabled);(previous?.isConnected?previous:canvas).focus({preventScroll:true});});
 function show(title,kind){world.atlas.resources.cancel();world.atlas.town.clear();gathering.cancel({clearSelection:true});world.cancelCameraMotion();view=kind;dialog.dataset.view=kind;dialog.querySelector('h2').textContent=title;dialog.querySelector('.vtown-body').replaceChildren();dialog.querySelector('[role=status]').textContent='';if(!dialog.open){enabled=cameraInputEnabled(world);previous=document.activeElement;controls.enabled=false;dialog.showModal();}dialog.querySelector('header button').focus();}
 function handoff(fn){dialog.addEventListener('close',fn,{once:true});close();}
 function directory(){if(!art||isBlocked())return false;show('雪松驿镇','directory');const body=dialog.querySelector('.vtown-body');body.append(el('p','石街围着驿钟，连接路图、炉火和货栈。老木屋与河桥仍在西南侧。'));for(const r of art.records){const card=el('article');card.append(el('h3',r.name),el('p',r.def.rooms.join(' · ')));card.append(button('查看外观',()=>handoff(()=>focus(r.type,-1))));for(const [i,name]of r.def.rooms.entries())card.append(button('进入'+name,()=>handoff(()=>focus(r.type,i))));body.append(card);}body.append(button('看广场与老木屋',()=>handoff(overview)));return true;}
 function focus(id,index=0){if(!art||isBlocked())return false;const r=art.records.find(r=>r.type===id);if(!r)return false;world.atlas.travel('valley');selected=r;room=index;if(index>=0){r.interior=r.rooms[index].eye;r.target=r.rooms[index].target;if(index===1){r.doors[1].open=true;r.doors[1].angle=-1.48;r.doors[1].root.rotation.y=-1.48;}}const ok=buildings.focus(r,index>=0,{lightScale:.22});renderPanel();return ok;}
 function overview(){if(!art||isBlocked())return false;world.atlas.travel('valley');world.cancelCameraMotion();camera.position.copy(art.root.localToWorld(new T.Vector3(-28,27,33)));controls.target.copy(art.root.localToWorld(new T.Vector3(0,5,-2)));camera.lookAt(controls.target);controls.update();return true;}
 function renderPanel(){if(!selected){panel.hidden=true;return;}panel.hidden=false;panel.dataset.building=selected.type;panel.dataset.room=String(room);panel.querySelector('strong').textContent=selected.name;const navEl=panel.querySelector('nav'),actions=panel.querySelector('.vtown-actions');navEl.replaceChildren();actions.replaceChildren();for(const [i,name]of [[-1,'外观'],...selected.def.rooms.map((n,i)=>[i,n])]){const b=button(name,()=>focus(selected.type,i));b.dataset.room=String(i);b.setAttribute('aria-pressed',String(i===room));navEl.append(b);}for(const [i,d]of selected.doors.entries()){const b=button((d.open?'关闭':'打开')+(i?'内门':'正门'),()=>{d.open=!d.open;renderPanel();});b.dataset.door=String(i);b.setAttribute('aria-pressed',String(d.open));actions.append(b);}const lamps=button(selected.lampsOn?'熄下吊灯':'点亮吊灯',()=>{selected.lampsOn=!selected.lampsOn;renderPanel();});lamps.dataset.action='lamps';actions.append(lamps);
 if(selected.type==='hall'){actions.append(button('查看驿站委托',()=>orders()),button('敲响驿钟',ringBell),button('阅读五境路图',()=>world.atlas.openMap()));}
 if(selected.type==='lodge'){actions.append(button(selected.fireOn?'熄下炉火':'添柴点火',()=>{selected.fireOn=!selected.fireOn;renderPanel();}));for(const[n,label]of [[false,'歇至晨光'],[true,'歇至月夜']])actions.append(button(label,()=>{environment.setNight(n);panel.querySelector('p').textContent=n?'窗外渐入月夜。':'窗外渐见晨光。';}));}
 if(selected.type==='storehouse')actions.append(button('交付驿站物资',()=>orders(true)),button('打开公共保管库',vault));panel.querySelector('p').textContent=room<0?'厚石基座、实木廊檐与积雪屋面':'拖动环顾 · 点击门扇和室内器物也可互动';
 }
 const itemName=id=>GOODS.find(g=>g.id===id)?.name||id;
 async function transact(fn,render){if(pending)return;pending=true;let result;try{const execute=()=>{if(disposed)return null;market.store.reload();return fn();};result=navigator.locks?await navigator.locks.request(MARKET_KEY,execute):execute();}catch{result={ok:false,message:'保存未完成，请重试。'};}pending=false;if(disposed)return;gathering.refreshBag();if(dialog.open){render();dialog.querySelector('[role=status]').textContent=result?.message||'操作已取消。';}}
 function orders(delivery=false){if(!art)return;show(delivery?'雪松货栈 · 物资交付':'北境驿务厅 · 冬季委托',delivery?'delivery':'orders');const body=dialog.querySelector('.vtown-body'),s=market.store.snapshot().valleyOrders,order=VALLEY_ORDERS[s.completed.length];body.append(el('p','驿站协作 '+s.completed.length+' / '+VALLEY_ORDERS.length+' · 委托按顺序开放；已交付记录保存在当前浏览器。'));if(!order){body.append(el('h3','三份冬季物资已备齐'),el('p','炉料、口粮和路灯已经交给驿站。旅行灯纪念品在行囊中，可以摆进你的客房。'));return;}body.append(el('h3',order.name),el('p',order.text));const state=market.store.snapshot();for(const[id,n]of Object.entries(order.input))body.append(el('p',itemName(id)+' × '+n+' · 行囊 '+state.bag[id]));body.append(el('p','回报：'+order.coins+' 枚铜币'+(order.reward?'、旅行灯 × 1':'')));
 if(!s.active){const b=button('接取这份委托',()=>transact(()=>market.store.acceptValleyOrder(),()=>orders(false)));b.dataset.orderAccept='true';b.disabled=delivery;body.append(b);if(delivery)body.append(button('到驿务厅接取',()=>handoff(()=>focus('hall',0))));}else if(delivery){const b=button('交付物资并领取回报',()=>transact(()=>market.store.deliverValleyOrder(),()=>orders(true)));b.dataset.orderDeliver='true';b.disabled=Object.entries(order.input).some(([id,n])=>state.bag[id]<n);body.append(b,el('p','交付时消耗以上随身材料；保管库中的物品须先取回。'));}else body.append(el('p','已接取，备齐物资后送往雪松货栈。'),button('到货栈交付',()=>handoff(()=>focus('storehouse',0))));body.append(button('寻找原料产地',()=>handoff(()=>world.atlas.resources.showDirectory())));
 }
 function vault(){if(!art)return;show('雪松货栈 · 公共保管库','vault');const body=dialog.querySelector('.vtown-body'),state=market.store.snapshot();body.append(el('p','与山城保管库共用你的私人库存。材料存入后不会用于随身加工或交付。'));let n=0;for(const g of GOODS){if(!state.bag[g.id]&&!state.vault[g.id])continue;n++;const row=el('article');row.dataset.item=g.id;row.append(el('h3',g.name),el('p','行囊 '+state.bag[g.id]+' · 保管库 '+state.vault[g.id]));for(const [to,label]of [[true,'存入一件'],[false,'取回一件']]){const b=button(label,()=>transact(()=>market.store.transfer(g.id,to),vault));b.disabled=!(to?state.bag[g.id]:state.vault[g.id]);b.dataset.transfer=to?'in':'out';row.append(b);}body.append(row);}if(!n)body.append(el('p','目前没有可寄存的物品。先去产地采收，或到工坊加工。'));}
 function ringBell(){if(!art)return;bellAt=performance.now();say('驿钟响过雪松街，回声渐远。');try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();for(const [f,g]of [[523.25,.06],[1046.5,.024],[1465,.012]]){const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.value=f;gain.gain.setValueAtTime(g,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+2.7);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+2.8);}}catch{}}
 function add(region,source){if(region.id!=='valley'||art)return;art=createValleyTown(settlements,source);for(const r of art.records)for(const d of r.doors)removers.push(nav.addDynamic(d.proxy));const card=document.querySelector('[data-region-card=valley]>div:last-child'),link=button('雪松驿镇',()=>{const map=document.querySelector('.atlas-map');if(map.open){map.addEventListener('close',directory,{once:true});map.close();}else directory();});link.dataset.valleyTown='true';card?.append(link);removers.push(()=>link.remove());}
 function reserveFlora(region){if(region.id==='valley'&&art)removers.push(gathering.flora.reserveWhere(p=>p.y<8&&art.clearAt(p.x-art.center[0],p.z-art.center[2])));}
 function clear(){selected=null;down=null;panel.hidden=true;hint.hidden=true;close();}
 panel.querySelector('header button').onclick=()=>{clear();buildings.close();};
 function ancestor(o,target){for(;o;o=o.parent)if(o===target)return true;return false;}
 function pointerUp(e){const start=down;down=null;if(!start||e.button!==0||Math.hypot(e.clientX-start[0],e.clientY-start[1])>6||!art||isBlocked()||document.body.dataset.visitorHidden==='true')return;const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);ray.far=65;const hit=ray.intersectObject(art.root,true).find(h=>h.object.visible);if(!hit)return;const r=art.records.find(r=>ancestor(hit.object,r.root));if(!r)return;const di=r.doors.findIndex(d=>ancestor(hit.object,d.root));if(nav.obstructed(camera.position,hit.point.clone().lerp(camera.position,.02),.005,null,di>=0?r.doors[di].proxy:null))return;if(hit.distance>12){queueMicrotask(()=>focus(r.type,-1));return;}if(di>=0){r.doors[di].open=!r.doors[di].open;if(selected===r)renderPanel();return;}let action=null;for(let o=hit.object;o;o=o.parent)if(o.userData.townAction){action=o.userData.townAction;break;}if(action==='bell'){ringBell();return;}if(action==='lamps'){r.lampsOn=!r.lampsOn;if(selected===r)renderPanel();return;}if(action==='orders'){orders();return;}if(action==='delivery'){orders(true);return;}const v=r.root.worldToLocal(hit.point.clone());if(r.type==='hall'&&v.z< -2.5&&v.y>.8&&v.y<1&&Math.abs(v.x)<1.4){world.atlas.openMap();return;}if(r.type==='storehouse'&&Math.abs(v.x)<1&&v.z< -2.85&&v.z> -4.2&&v.y<1){vault();return;}if(r.type==='lodge'&&v.x< -1.7&&v.z> -1&&v.z<.2&&v.y<2){r.fireOn=!r.fireOn;if(selected===r)renderPanel();return;}if(buildings.selected!==r.id)queueMicrotask(()=>focus(r.type,-1));}
 const pd=e=>{if(e.button===0)down=[e.clientX,e.clientY];},release=()=>down=null,key=e=>{if(e.code==='Escape'&&!dialog.open)clear();},storage=e=>{if(e.key===MARKET_KEY){market.store.reload();if(dialog.open){if(view==='vault')vault();if(view==='orders'||view==='delivery')orders(view==='delivery');}}};canvas.addEventListener('pointerdown',pd);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',release);window.addEventListener('blur',release);window.addEventListener('keydown',key);window.addEventListener('storage',storage);
 function update(){if(!art)return;const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;for(const r of art.records){for(const d of r.doors){d.angle=reduced.matches?(d.open?-1.48:0):T.MathUtils.damp(d.angle,d.open?-1.48:0,7,dt);d.root.rotation.y=d.angle;}const near=camera.position.distanceTo(r.root.getWorldPosition(new T.Vector3()))<35;for(const l of r.lights)l.intensity=near&&r.lampsOn?28:0;r.filament.emissiveIntensity=r.lampsOn?.65:0;if(r.hearth){r.hearth.setLit(r.fireOn);r.hearth.update(now,reduced.matches,camera);}else r.fire.intensity=0;if(r.bell){const age=(now-bellAt)/1000;r.bell.rotation.x=!reduced.matches&&age<4?Math.sin(age*8)*.20*Math.exp(-age*.8):0;}}
 if(buildings.selected&&buildings.selected!==selected?.id){const r=art.records.find(r=>r.id===buildings.selected);selected=r||null;if(r){room=buildings.inside?Math.max(0,room):-1;renderPanel();}else panel.hidden=true;}if(selected&&!buildings.selected){selected=null;panel.hidden=true;}if(isBlocked()||selected||document.body.dataset.visitorHidden==='true'){hint.hidden=true;return;}const pos=art.root.localToWorld(new T.Vector3(0,6,0)),v=pos.clone().project(camera);hint.hidden=pos.distanceTo(camera.position)>90||v.z< -1||v.z>1||Math.abs(v.x)>.85||Math.abs(v.y)>.8;if(!hint.hidden){hint.style.left=T.MathUtils.clamp((v.x*.5+.5)*innerWidth,120,innerWidth-120)+'px';hint.style.top=T.MathUtils.clamp((-v.y*.5+.5)*innerHeight,130,innerHeight-260)+'px';}}
 return{add,reserveFlora,update,clear,focus,overview,directory,orders,vault,ringBell,get architecture(){return art;},stats:()=>({selected:selected?.type,room,orders:market.store.snapshot().valleyOrders,removedInstances:art?.removed.length,buildings:art?.records.map(r=>({id:r.type,doors:r.doors.map(d=>({open:d.open,angle:d.angle})),lamps:r.lampsOn,fire:r.fireOn}))}),dispose(){disposed=true;clear();removers.forEach(fn=>fn());art?.dispose();audio?.close();[dialog,panel,hint].forEach(n=>n.remove());canvas.removeEventListener('pointerdown',pd);canvas.removeEventListener('pointerup',pointerUp);canvas.removeEventListener('pointercancel',release);window.removeEventListener('blur',release);window.removeEventListener('keydown',key);window.removeEventListener('storage',storage);}};
}
