import {cameraInputEnabled,restoreCameraInput} from './camera-input.js';
import * as T from 'three';
import {createFerry} from './ferry.js';
import {createWaterfrontArchitecture} from './waterfront-architecture.js';
import './waterfront-quarter.css';

const KEY='aether.waterfront.v1';
const PAGES=[
 ['水庭建造札记','亭台之间的月桥保留着最初的弧线。新街区立在前湾木桩与石墩上，接向西岸入口步道；桥下仍是同一片湖水。','书记馆收藏海图，旅舍面向远帆，舟会保管绳索、木料与船具。沿水面的长街把三个门厅连接起来。'],
 ['潮汐与航路','晨间出发的舟船先沿西岸行驶，再转入亭台之间的水道。岸边标灯用于辨认码头入口。','白帆旅舍的灯笼总在黄昏亮起。舟会每日检查舷梯锁链，在风大的日子提前将船系回桩上。'],
 ['旅人的留页','愿每一次归航，都有人记得窗里的灯。','空白页还留着上一个旅人的短句。把这一页折起，留待下次归来再读。'],
];
export function createWaterfrontQuarter(world,{settlements,nav,buildings,gathering,isBlocked,say,environment}){
 const {camera,controls}=world,canvas=world.renderer.domElement,reduced=matchMedia('(prefers-reduced-motion: reduce)'),ray=new T.Raycaster(),ndc=new T.Vector2();let ferry=null,art=null,selected=null,room=0,last=performance.now(),down=null,bookmark=0,page=0,saved=true,prior=null,enabled=true;const removers=[];
 try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');if(Number.isInteger(raw.bookmark))bookmark=T.MathUtils.clamp(raw.bookmark,0,PAGES.length-1);}catch{saved=false;}
 const panel=document.createElement('section');panel.className='quarter-panel';panel.hidden=true;panel.setAttribute('aria-label','临水建筑互动');panel.innerHTML='<header><div><small>临水街区</small><strong></strong></div><button data-quarter="close" aria-label="关闭临水建筑互动">×</button></header><nav aria-label="临水房间视角"></nav><div class="quarter-actions"></div><p role="status"></p>';document.body.append(panel);
 const dialog=document.createElement('dialog');dialog.className='quarter-dialog';dialog.setAttribute('aria-labelledby','quarter-title');dialog.innerHTML='<header><div><small>精灵水庭 · 前湾</small><h2 id="quarter-title"></h2></div><button aria-label="关闭临水街区窗口">×</button></header><div class="quarter-body"></div><p role="status"></p>';document.body.append(dialog);
 const hint=document.createElement('button');hint.className='quarter-hint';hint.textContent='临水街区 · 走近看看';hint.hidden=true;document.body.append(hint);
 const el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;},button=(label,fn)=>{const b=el('button',label);b.type='button';b.onclick=fn;return b;};
 function closeDialog(){if(dialog.open)dialog.close();}
 dialog.querySelector('header button').onclick=closeDialog;dialog.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))restoreCameraInput(world,enabled);(prior?.isConnected?prior:canvas).focus({preventScroll:true});});
 function show(title){world.atlas?.resources?.cancel();gathering.cancel({clearSelection:true});world.cancelCameraMotion();dialog.querySelector('h2').textContent=title;dialog.querySelector('.quarter-body').replaceChildren();dialog.querySelector('[role=status]').textContent='';if(!dialog.open){prior=document.activeElement;enabled=cameraInputEnabled(world);controls.enabled=false;dialog.showModal();}dialog.querySelector('header button').focus();}
 function handoff(fn){dialog.addEventListener('close',fn,{once:true});closeDialog();}
 function directory(){if(isBlocked())return false;show('临水街区');const body=dialog.querySelector('.quarter-body');body.append(el('p','从旧月的书页，到白帆的窗灯。沿码头长街，走进水庭的三个门厅。'));if(!art){body.append(el('p','水庭正在展开，请稍候再来。'));return true;}for(const r of art.records){const section=el('article');section.append(el('h3',r.name),el('p',r.def.rooms.join(' · ')),button('查看外观',()=>handoff(()=>focus(r.type,-1))),button('进入'+r.def.rooms[0],()=>handoff(()=>focus(r.type,0))));body.append(section);}body.append(button('俯瞰临水街区',()=>handoff(overview)),button('晨露渡舟 · 随船游览',()=>handoff(()=>ferry.board())));return true;}
 function focus(id,index=0){if(isBlocked()||!art)return false;const r=art.records.find(r=>r.type===id);if(!r)return false;world.atlas.travel('watercourt');selected=r;room=index;if(index>=0){r.interior=r.rooms[index].eye;r.target=r.rooms[index].target;if(index===1){r.doors[1].open=true;r.doors[1].angle=r.doors[1].target;r.doors[1].root.rotation.y=r.doors[1].angle;}}buildings.focus(r,index>=0,{lightScale:0});renderPanel();return true;}
 function overview(){if(!art||isBlocked())return false;clear();buildings.close();world.atlas.travel('watercourt');world.cancelCameraMotion();camera.position.copy(art.root.localToWorld(new T.Vector3(33,23,20)));controls.target.copy(art.root.localToWorld(new T.Vector3(0,3,40)));camera.lookAt(controls.target);controls.update();return true;}
 function setDoor(i,value){if(!selected)return;selected.doors[i].open=!!value;renderPanel();}
 function renderPanel(){if(!selected){panel.hidden=true;return;}panel.hidden=false;panel.dataset.building=selected.type;panel.dataset.room=String(room);panel.querySelector('strong').textContent=selected.name;const views=panel.querySelector('nav');views.replaceChildren();for(const [i,label] of [[-1,'外观'],...selected.def.rooms.map((name,i)=>[i,name])]){const b=button(label,()=>focus(selected.type,i));b.setAttribute('aria-pressed',String(room===i));b.dataset.room=String(i);views.append(b);}const actions=panel.querySelector('.quarter-actions');actions.replaceChildren();for(const [i,d] of selected.doors.entries()){const b=button((d.open?'关闭':'打开')+(i?'内门':'正门'),()=>setDoor(i,!d.open));b.dataset.door=String(i);b.setAttribute('aria-pressed',String(d.open));actions.append(b);}for(const [id,label,key] of [['windows','百叶窗','windowsOpen'],['lamps','室内灯','lampsOn']]){const b=button(label,()=>{selected[key]=!selected[key];renderPanel();});b.dataset.toggle=id;b.setAttribute('aria-pressed',String(selected[key]));actions.append(b);}if(selected.type==='archive'){const b=button('翻阅《水庭札记》',readBook);b.dataset.action='book';actions.append(b);}if(selected.type==='inn'){const heat=button(selected.fireOn?'熄下炉火':'添柴点火',()=>{selected.fireOn=!selected.fireOn;renderPanel();});heat.dataset.toggle='hearth';heat.setAttribute('aria-pressed',String(selected.fireOn));actions.append(heat);for(const [night,label] of [[false,'歇至晨光'],[true,'歇至月夜']]){const b=button(label,()=>{environment.setNight(night);panel.querySelector('[role=status]').textContent=night?'窗外渐入月夜。':'窗外渐见晨光。';});b.dataset.rest=String(night);actions.append(b);}}if(selected.type==='harbor'){const b=button(art.gangOpen?'升起舷梯':'放下舷梯',()=>{ferry.toggleGang();renderPanel();});b.dataset.action='gangplank';actions.append(b);actions.append(button('查看泊舟',viewBoat));}panel.querySelector('[role=status]').textContent=room>=0?selected.def.rooms[room]+' · 拖动原地环顾，滚轮调整视野':'沿前廊进入门厅';}
 function viewBoat(){return ferry?.board();}
 function readBook(){if(isBlocked())return;page=bookmark;show('水庭札记');renderBook();}
 function renderBook(){const body=dialog.querySelector('.quarter-body');body.replaceChildren();dialog.dataset.page=String(page);body.append(el('small',`第 ${page+1} / ${PAGES.length} 页`),el('h3',PAGES[page][0]));for(const text of PAGES[page].slice(1))body.append(el('p',text));const prev=button('上一页',()=>{page--;renderBook();}),next=button('下一页',()=>{page++;renderBook();}),mark=button('留在这一页',()=>{try{localStorage.setItem(KEY,JSON.stringify({bookmark:page}));bookmark=page;saved=true;}catch{saved=false;}dialog.querySelector('[role=status]').textContent=saved?'书签已留在第 '+(page+1)+' 页。':'书签未能保存，请稍后重试。';});prev.disabled=page===0;next.disabled=page===PAGES.length-1;mark.dataset.bookmark='save';body.append(prev,next,mark);}
 panel.querySelector('[data-quarter=close]').onclick=()=>{clear();buildings.close();};hint.onclick=directory;
 function add(region,parent){if(region.id!=='watercourt'||art)return;art=createWaterfrontArchitecture(settlements,parent);ferry=createFerry(world,art,{nav,isBlocked,say,buildings});for(const r of art.records)for(const d of r.doors)removers.push(nav.addDynamic(d.proxy));removers.push(nav.addDynamic(art.gangProxy,{walkable:true}));const mapCard=document.querySelector('[data-region-card=watercourt]>div:last-child');const link=button('临水街区',()=>{const map=document.querySelector('.atlas-map');if(map.open){map.addEventListener('close',directory,{once:true});map.close();}else directory();});link.dataset.quarterDirectory='true';mapCard?.append(link);removers.push(()=>link.remove());}
 function clear(){ferry?.unfollow();selected=null;down=null;panel.hidden=true;hint.hidden=true;delete panel.dataset.boat;closeDialog();}
 function hit(e){if(!art||isBlocked()||document.body.dataset.visitorHidden==='true')return null;const rect=canvas.getBoundingClientRect();ndc.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(ndc,camera);ray.far=65;const hits=ray.intersectObject(art.root,true).filter(h=>h.object.visible);if(!hits.length)return null;const approach=hits[0].point.clone().lerp(camera.position,.025);if(nav.obstructed(camera.position,approach,.005))return null;let o=hits[0].object;while(o){if(o.userData.quarterAction)return{record:art.records.find(r=>r.type==='harbor'),action:o.userData.quarterAction,hit:hits[0]};const r=art.records.find(r=>r.root===o);if(r)return{record:r,hit:hits[0]};o=o.parent;}return null;}
 function ancestor(object,target){while(object){if(object===target)return true;object=object.parent;}return false;}
 function rest(){show('白帆旅舍 · 临水客房');const body=dialog.querySelector('.quarter-body');body.append(el('p','收好行囊，听一会儿窗外的水声。醒来时，想看晨光还是月色？'));for(const [night,label] of [[false,'歇至晨光'],[true,'歇至月夜']])body.append(button(label,()=>{environment.setNight(night);closeDialog();}));}
 const pd=e=>{if(e.button===0)down=[e.clientX,e.clientY];},pu=e=>{const start=down;down=null;if(!start||e.button!==0||Math.hypot(e.clientX-start[0],e.clientY-start[1])>6)return;const h=hit(e);if(!h)return;const r=h.record,close=h.hit.distance<12,doorIndex=r.doors.findIndex(d=>ancestor(h.hit.object,d.root));
  if(close&&h.action==='gangplank'){if(!ferry.toggleGang())return;if(selected?.type==='harbor')renderPanel();say(art.gangOpen?'正在放下舷梯。':'正在升起舷梯。');return;}
  if(close&&doorIndex>=0){r.doors[doorIndex].open=!r.doors[doorIndex].open;if(selected===r)renderPanel();return;}
  if(close&&r.shutters.some(s=>ancestor(h.hit.object,s.root))){r.windowsOpen=!r.windowsOpen;if(selected===r)renderPanel();return;}
  const point=r.root.worldToLocal(h.hit.point.clone());if(close&&r.type==='inn'&&point.x>-3.15&&point.x<-.85&&point.z>-1&&point.z<.2&&point.y<2){r.fireOn=!r.fireOn;if(selected===r)renderPanel();return;}
  if(close&&r.type==='archive'&&Math.abs(point.x-1.4)<.52&&Math.abs(point.z-2.9)<.42&&point.y>.7&&point.y<1){readBook();return;}
  if(close&&r.type==='archive'&&Math.abs(point.x-.2)<1&&Math.abs(point.z+3.3)<.65&&point.y>.8&&point.y<1){world.atlas.openMap();return;}
  if(close&&r.type==='inn'&&point.x> -3.25&&point.x< -1.55&&point.z> -4.7&&point.z< -2.1&&point.y>.35&&point.y<2.8){rest();return;}
  if(close&&/悬灯/.test(h.hit.object.name)){r.lampsOn=!r.lampsOn;if(selected===r)renderPanel();return;}
  if(buildings.selected!==r.id)queueMicrotask(()=>focus(r.type,-1));
 };
 const release=()=>down=null,escape=e=>{if(e.code==='Escape'&&!dialog.open){clear();}};canvas.addEventListener('pointerdown',pd);canvas.addEventListener('pointerup',pu);canvas.addEventListener('pointercancel',release);window.addEventListener('blur',release);window.addEventListener('keydown',escape);
 function update(){if(!art)return;const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;for(const r of art.records){for(const d of r.doors){d.angle=T.MathUtils.damp(d.angle,d.open?d.target:0,7,dt);d.root.rotation.y=d.angle;}for(const s of r.shutters)s.root.rotation.y=T.MathUtils.damp(s.root.rotation.y,s.base+(r.windowsOpen?s.target:0),7,dt);if(r.hearth){r.hearth.setLit(r.fireOn);r.hearth.update(now,reduced.matches,camera);}const nearby=camera.position.distanceTo(r.root.getWorldPosition(new T.Vector3()))<35;for(const l of r.lights)l.intensity=nearby&&r.lampsOn?48:0;r.filament.emissiveIntensity=r.lampsOn?.65:0;r.daylight.intensity=nearby&&r.windowsOpen?22*(1-environment.nightBlend*.94):0;}
 art.gangAngle=T.MathUtils.damp(art.gangAngle,art.gangOpen?-.337:1.2,5,dt);art.gangplank.rotation.z=art.gangAngle;ferry.update();
 // Preserve the contextual controls only while their building is being inspected.
 if(buildings.selected&&buildings.selected!==selected?.id){const record=art.records.find(r=>r.id===buildings.selected);selected=record||null;if(record){room=buildings.inside?Math.max(0,room):-1;renderPanel();}else panel.hidden=true;}if(selected&&!buildings.selected&&panel.dataset.boat!=='true'){selected=null;panel.hidden=true;}if(isBlocked()||selected||document.body.dataset.visitorHidden==='true'){hint.hidden=true;return;}const p=art.root.localToWorld(new T.Vector3(0,2,34)),v=p.clone().project(camera);const visible=camera.position.distanceTo(p)<100&&v.z>-1&&v.z<1&&Math.abs(v.x)<.82&&Math.abs(v.y)<.8;hint.hidden=!visible;if(visible){hint.style.left=T.MathUtils.clamp((v.x*.5+.5)*innerWidth,110,innerWidth-110)+'px';hint.style.top=T.MathUtils.clamp((-v.y*.5+.5)*innerHeight,130,innerHeight-260)+'px';}}
 return{add,focus,overview,directory,update,clear,readBook,setDoor,get ferry(){return ferry;},get records(){return art?.records||[];},get architecture(){return art;},stats:()=>({selected:selected?.type||null,room,bookmark,saved,gangOpen:art?.gangOpen,gangAngle:art?.gangAngle,buildings:art?.records.map(r=>({id:r.type,doors:r.doors.map(d=>({open:d.open,angle:d.angle})),windows:r.windowsOpen,lamps:r.lampsOn}))||[]}),dispose(){clear();ferry?.dispose();removers.forEach(fn=>fn());art?.dispose();panel.remove();dialog.remove();hint.remove();canvas.removeEventListener('pointerdown',pd);canvas.removeEventListener('pointerup',pu);canvas.removeEventListener('pointercancel',release);window.removeEventListener('blur',release);window.removeEventListener('keydown',escape);}};
}
