import * as T from 'three';
import assert from 'node:assert/strict';
import {createNavigation} from '../src/atlas/navigation.js';
const box=(name,size,position)=>{const m=new T.Mesh(new T.BoxGeometry(...size),new T.MeshBasicMaterial());m.name=name;m.position.set(...position);return m;};
const ground=()=>box('Ground floor',[20,.2,20],[0,-.1,0]);
const nav=createNavigation(),world=new T.Group();world.add(ground(),box('Stone low wall',[.04,.8,8],[1,.4,0]));nav.add(world);
const start=new T.Vector3(0,0,0);assert(!nav.walk(start,1.8,0),'Large steps must not tunnel through a low wall');assert.deepEqual(start.toArray(),[0,0,0]);
assert(!nav.canFly(new T.Vector3(0,.1,0),new T.Vector3(2,.1,0)),'Flight feet must collide with a low wall below eye level');
assert(nav.canFly(new T.Vector3(0,1.5,0),new T.Vector3(2,1.5,0)),'Clear flight above the wall remains possible');
assert(!nav.canFly(new T.Vector3(0,2,0),new T.Vector3(0,-1,0)),'Descending must stop above solid ground');
assert(nav.walk(start,-.6,0),'Unobstructed floor remains walkable');
const cameraNav=createNavigation(),post=box('Timber post',[.04,2,.1],[1,1,0]);cameraNav.add(post);
assert(cameraNav.obstructed(new T.Vector3(0,1.5,.3),new T.Vector3(2,1.5,.3),.28),'Camera boom radius catches off-axis geometry');
assert(!cameraNav.obstructed(new T.Vector3(0,1.5,.5),new T.Vector3(2,1.5,.5),.28),'Camera outside post clearance remains free');
const treeNav=createNavigation(),trees=new T.Group();trees.add(ground(),box('Horncrest pine trunk',[.4,4,.4],[1,2,0]));treeNav.add(trees);
assert(!treeNav.walk(new T.Vector3(0,0,0),2,0),'Tree trunk must not be excluded as foliage');
const ledgeNav=createNavigation();ledgeNav.add(box('Ground ledge',[.14,.2,3],[0,-.1,0]));assert(!ledgeNav.walk(new T.Vector3(0,0,0),0,.1),'Both boots need support');
const floatingNav=createNavigation(),island=new T.Group();island.userData.floating=true;island.add(ground());floatingNav.add(island);island.position.y=.4;island.updateMatrixWorld(true);floatingNav.sync();assert(Math.abs(floatingNav.height(0,0)-.4)<1e-5,'Floating ground tracks actual current height');
const safe=treeNav.landing(1,0,0,3);assert(safe&&treeNav.clearBody(safe),'Landing has room for the body');
console.log('ATLAS_COLLISION_PASS: swept body, ground descent, walls, trees, camera radius, ledge support and moving-platform landing.');
