import {chromium} from 'playwright';import fs from 'node:fs';import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:'/Users/ziyu/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',args:['--use-angle=metal']});
const page=await browser.newPage({viewport:{width:1536,height:1024},deviceScaleFactor:1});const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://127.0.0.1:5175/dist-watercourt/lake.html');await page.waitForFunction(()=>window.__watercourt?.ready,null,{timeout:120000});await page.locator('.loading').waitFor({state:'detached'});
await page.screenshot({path:'outputs/watercourt/website-desktop.png'});
for(let i=0;i<4;i++){await page.locator(`[data-chapter="${i}"]`).click();await page.waitForFunction(i=>Math.abs(window.__watercourt.stats().progress-i/3)<.001,i);assert.equal(await page.locator(`[data-chapter="${i}"]`).getAttribute('aria-current'),'step');await page.screenshot({path:`work/watercourt/chapter-${i}.png`});}checks.push('Four chapter buttons move the real camera and update active state.');
await page.getByRole('button',{name:'暂停动画'}).click();const a=await page.evaluate(()=>window.__watercourt.stats().time);await page.waitForTimeout(500);const b=await page.evaluate(()=>window.__watercourt.stats().time);assert.equal(a,b);await page.getByRole('button',{name:'播放动画'}).click();await page.waitForTimeout(350);assert.ok((await page.evaluate(()=>window.__watercourt.stats().time))>b);checks.push('Pause freezes shader and particle time; play resumes.');
await page.locator('.sound').click();assert.equal(await page.locator('.sound').getAttribute('aria-pressed'),'true');await page.locator('.sound').click();checks.push('Sound toggles on and off.');
await page.getByRole('button',{name:'关于',exact:true}).click();assert.ok(await page.locator('#panel').isVisible());await page.keyboard.press('Escape');assert.equal(await page.locator('#panel').isVisible(),false);checks.push('About dialog opens and Escape closes it.');
await page.getByRole('button',{name:'作品',exact:true}).click();await page.locator('[data-visit="1"]').click();await page.waitForFunction(()=>Math.abs(window.__watercourt.stats().progress-1/3)<.005);assert.equal(await page.locator('#panel').isVisible(),false);checks.push('A work opens its corresponding 3D location.');
await page.mouse.move(900,350);await page.mouse.down();await page.mouse.move(1060,390,{steps:8});await page.mouse.up();await page.waitForTimeout(800);assert.ok(Math.abs(await page.evaluate(()=>window.__watercourt.stats().yaw))>.1);checks.push('Dragging changes viewing direction.');
const before=await page.evaluate(()=>window.__watercourt.stats().progress);await page.mouse.wheel(0,500);await page.waitForTimeout(1600);assert.ok((await page.evaluate(()=>window.__watercourt.stats().progress))>before);checks.push('Wheel advances along the camera route.');
await page.locator('.cta').first().click();const tp=await page.evaluate(()=>window.__watercourt.stats());assert.ok(tp.touring&&tp.playing);await page.waitForTimeout(600);assert.ok((await page.evaluate(()=>window.__watercourt.stats().progress))>tp.progress);await page.locator('.cta').first().click();checks.push('Tour starts, advances and stops.');
await page.getByRole('button',{name:'返回林间入口'}).click();await page.waitForFunction(()=>window.__watercourt.stats().progress<.001);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'outputs/watercourt/website-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
for(const sel of ['.hero','.header','.footer']){const box=await page.locator(sel).boundingBox();assert.ok(box.x>=0&&box.x+box.width<=391&&box.y>=0&&box.y+box.height<=845);}
await page.locator('[data-chapter="2"]').click();await page.waitForFunction(()=>Math.abs(window.__watercourt.stats().progress-2/3)<.005);checks.push('390×844 mobile: no overflow; all four destinations usable.');
await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.waitForFunction(()=>window.__watercourt?.ready);assert.equal(await page.evaluate(()=>window.__watercourt.stats().playing),false);checks.push('Reduced-motion preference starts with animation paused.');
assert.deepEqual(errors,[]);const stats=await page.evaluate(()=>window.__watercourt.stats());fs.writeFileSync('outputs/watercourt/verification.json',JSON.stringify({checks,errors,stats,viewports:[[1536,1024],[390,844]],method:'IAB initial inspection; Chromium Metal fallback after IAB tab session failure'},null,2));console.log(JSON.stringify({checks,errors,stats}));await browser.close();
